import {chromium,expect} from '@playwright/test';
import {createAndSkip} from './qa-setup-helper.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
const out=path.resolve('../research/verification'),origin='http://127.0.0.1:8001',browser=await chromium.launch({channel:'chrome',headless:true}),errors=[],checks={};
const context=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce'}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));
const call=async(url,method='GET',body)=>p.evaluate(async({url,method,body})=>{const r=await fetch('/api'+url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()}},{url,method,body});
async function shot(name,width=1440){await p.setViewportSize({width,height:width===390?844:1100});if(await p.locator('.agenda-dialog').count())await p.locator('.agenda-dialog').evaluate(e=>e.scrollTop=0);await p.screenshot({path:path.join(out,name+'.png'),fullPage:true});if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error(name+' overflows');}
const dialog=()=>p.getByRole('dialog'),bell=()=>p.getByRole('button',{name:/^Bildirimler/});
const body=t=>Object.fromEntries(['title','notes','due_local','timezone','priority','estimate_minutes','remind_before','assignee_id'].map(k=>[k,t[k]]));
async function task(title,reminder=false){await p.getByRole('button',{name:'Yapılacak ekle',exact:true}).click();await dialog().getByLabel('Yapılacak işin adı',{exact:true}).fill(title);await dialog().getByLabel('İşin tahmini süresi',{exact:true}).fill('30');if(reminder){await dialog().getByLabel('İşin tarihi',{exact:true}).fill(new Date(Date.now()-120000).toISOString().slice(0,16));await dialog().getByLabel('İşin saat dilimi',{exact:true}).fill('UTC');await dialog().getByLabel('İşin hatırlatması',{exact:true}).selectOption('0');await dialog().getByLabel('İşin önceliği',{exact:true}).selectOption('high')}await dialog().getByRole('button',{name:'Ajandama ekle',exact:true}).click();await expect(dialog()).toHaveCount(0);await expect(p.locator('.agenda-task').filter({hasText:title})).toBeVisible()}
try{
 await p.goto(origin+'/app',{waitUntil:'networkidle'});await p.getByLabel('Adın',{exact:true}).fill('TEST Ajanda');await p.getByLabel('E-posta',{exact:true}).fill(`agenda-${Date.now()}@example.test`);await p.getByLabel('Parola',{exact:true}).fill('Browser-agenda-123456');await p.getByRole('button',{name:'Çalışma alanımı oluştur',exact:true}).click();await createAndSkip(p,'TEST · Günlük işlerim','personal');if(!(await call('/test/pilot','POST')).data.synthetic_test_only)throw Error('Isolated model app required');const wid=(await call('/workspaces')).data[0].id,base=`/workspaces/${wid}/agenda`;
 await p.getByRole('button',{name:'Ajandam',exact:true}).click();await expect(p.getByRole('heading',{name:'Ajandam',exact:true})).toBeVisible();await task('Müşteri teklifini kontrol et',true);await task('Sunum başlıklarını toparla');
 await p.getByRole('button',{name:'Zaman ayır',exact:true}).click();await dialog().getByLabel('Takvim başlığı',{exact:true}).fill('Sunum için odak zamanı');await p.keyboard.press('Escape');await expect(dialog()).toContainText('Takvim değişikliklerin henüz kaydedilmedi.');await dialog().getByRole('button',{name:'Düzenlemeye dön',exact:true}).click();await dialog().getByRole('button',{name:'Zamanı ayır',exact:true}).click();await expect(dialog()).toHaveCount(0);await expect(p.locator('.agenda-event')).toContainText('Sunum için odak zamanı');await p.locator('.agenda-event').click();await dialog().getByLabel('Takvim başlığı',{exact:true}).fill('Sunum için 1 saat odaklan');await dialog().getByRole('button',{name:'Kaydet',exact:true}).click();await expect(p.locator('.agenda-event')).toContainText('Sunum için 1 saat odaklan');checks.local_calendar_create_edit=true;
 await shot('agenda-desktop');await shot('agenda-tablet',1024);await shot('agenda-mobile',390);await p.setViewportSize({width:1440,height:1100});
 await expect(bell()).toHaveAttribute('aria-label','Bildirimler · 1 okunmamış',{timeout:15000});await bell().click();await p.getByLabel('Bildirim türü',{exact:true}).selectOption('agenda');await expect(dialog()).toContainText('Ajandandan bir hatırlatma');await dialog().locator('.notice-row').click();await expect(dialog().getByLabel('Yapılacak işin adı',{exact:true})).toHaveValue('Müşteri teklifini kontrol et');const tid=new URL(p.url()).searchParams.get('task');if(!tid)throw Error('Missing exact task link');await p.reload();await expect(dialog().getByLabel('Yapılacak işin adı',{exact:true})).toHaveValue('Müşteri teklifini kontrol et');await shot('agenda-task-mobile',390);await p.setViewportSize({width:1440,height:1100});await dialog().getByRole('button',{name:'Kapat',exact:true}).click();if(new URL(p.url()).searchParams.has('task'))throw Error('Task link not cleared');checks.reminder_exact_task_and_refresh=true;
 await p.getByRole('button',{name:'Müşteri teklifini kontrol et işini tamamla',exact:true}).click();await expect(p.locator('.agenda-task').filter({hasText:'Müşteri teklifini kontrol et'})).toHaveCount(0);if((await call('/notifications?kind=agenda')).data.items.length)throw Error('Completed reminder visible');await p.getByRole('button',{name:'Bitenler',exact:true}).click();await expect(p.locator('.agenda-task')).toContainText('Müşteri teklifini kontrol et');await p.getByRole('button',{name:'Müşteri teklifini kontrol et işini arşivle',exact:true}).click();await p.getByRole('button',{name:'Arşiv',exact:true}).click();await expect(p.locator('.agenda-task')).toContainText('Müşteri teklifini kontrol et');await p.getByRole('button',{name:'Müşteri teklifini kontrol et işini arşivden çıkar',exact:true}).click();await p.getByRole('button',{name:'Bitenler',exact:true}).click();await expect(p.locator('.agenda-task')).toContainText('Müşteri teklifini kontrol et');checks.complete_archive_restore_and_invalidated_reminder=true;
 await p.getByRole('button',{name:'Günüm',exact:true}).click();await p.getByRole('button',{name:'Birlikte planlayalım',exact:true}).click();await p.getByLabel('Planlanacak işler',{exact:true}).fill('TEST_AGENDA_PLAN · Bugünün önceliklerine göre düzenlenebilir yapılacaklar hazırla.');await p.getByRole('button',{name:'Planımı hazırla',exact:true}).click();await expect(p.locator('.chat-answer')).toContainText('3 yapılacak işten oluşan planın hazır',{timeout:20000});await p.getByRole('button',{name:'Ajanda planını incele',exact:true}).click();await expect(dialog()).toContainText('TEST · Günlük planım');const pid=new URL(p.url()).searchParams.get('plan');if(!pid)throw Error('Missing plan link');await p.reload();await expect(dialog()).toContainText('TEST · Günlük planım');await dialog().getByLabel('3. işi plana dahil et',{exact:true}).uncheck();await p.keyboard.press('Escape');await expect(dialog()).toContainText('Plan değişikliklerin henüz kaydedilmedi.');await dialog().getByRole('button',{name:'Düzenlemeye dön',exact:true}).click();checks.unsaved_plan_and_event_preserved=true;await dialog().getByLabel('Yapılacak işin adı',{exact:true}).first().fill('Sunumu 3 bölüme ayır');await shot('agenda-plan-desktop');await shot('agenda-plan-mobile',390);await p.setViewportSize({width:1440,height:1100});
 let lost=false;await p.route('**/agenda/plans/*/apply',async route=>{if(lost)return route.continue();lost=true;const response=await route.fetch();if(response.status()!==200)throw Error('Apply before lost response failed');await route.abort('failed')});
 await dialog().getByRole('button',{name:'Seçtiğim 2 işi ajandama ekle',exact:true}).click();await expect(dialog().getByRole('alert')).toBeVisible();const committed=(await call(base+`/plans/${pid}`)).data.task_ids;if(committed.length!==2)throw Error('Plan not committed before response loss');await dialog().getByRole('button',{name:'Seçtiğim 2 işi ajandama ekle',exact:true}).click();await expect(dialog()).toContainText('Bu plan ajandaya eklendi.');if(JSON.stringify((await call(base+`/plans/${pid}`)).data.task_ids)!==JSON.stringify(committed))throw Error('Retry duplicated tasks');await p.unroute('**/agenda/plans/*/apply');checks.review_select_edit_and_response_loss_idempotency=true;
 await dialog().getByRole('button',{name:'1. işi aç',exact:true}).click();await expect(dialog().getByLabel('Yapılacak işin adı',{exact:true})).toHaveValue('Sunumu 3 bölüme ayır');const current=(await call(base+'/tasks/'+committed[0])).data;await dialog().getByLabel('İşin notları',{exact:true}).fill('Benim henüz kaydetmediğim not');await call(base+'/tasks/'+committed[0],'PUT',{...body(current),title:'Diğer sekmede güncellenen iş',expected_revision:current.revision});await dialog().getByRole('button',{name:'Değişiklikleri kaydet',exact:true}).click();await expect(dialog().getByRole('alert')).toContainText('Bu iş değişti');await dialog().getByRole('button',{name:'Değişikliklerimi bırak, son sürümü aç',exact:true}).click();await expect(dialog().getByLabel('Yapılacak işin adı',{exact:true})).toHaveValue('Diğer sekmede güncellenen iş');await dialog().getByRole('button',{name:'Kapat',exact:true}).click();await p.getByRole('button',{name:'Diğer sekmede güncellenen iş işini tamamla',exact:true}).click();checks.stale_edit_recovery=true;
 await p.goto(origin+'/app?'+new URLSearchParams({workspace:wid,view:'calendar',plan:pid}));await dialog().getByRole('link',{name:'Sohbette devam et',exact:true}).click();await p.getByLabel('Sohbet mesajı',{exact:true}).fill('TEST · Planımın güncel durumunu özetle.');await p.getByRole('button',{name:'Gönder',exact:true}).click();await expect(p.locator('.chat-answer').last()).toContainText('TEST YANITI',{timeout:20000});const recorded=JSON.parse(await fs.readFile(path.join(out,'agenda-model-requests.json'),'utf8'));const latest=recorded.requests.at(-1).input[0].content;if(!latest.includes('Diğer sekmede güncellenen iş')||!latest.includes('"status": "done"')||!latest.includes('"applied": true'))throw Error('Followup lost current agenda state');checks.current_plan_state_in_followup_context=true;
 await p.getByRole('button',{name:'Yapılacak iş oluştur',exact:true}).last().click();await expect(dialog().getByLabel('İşin notları',{exact:true})).toContainText('TEST YANITI');await dialog().getByRole('button',{name:'Ajandama ekle',exact:true}).click();await expect(dialog()).toHaveCount(0);checks.plain_answer_to_editable_task=true;
 if(errors.length)throw Error(errors.join('; '));await fs.writeFile(path.join(out,'agenda-browser-results.json'),JSON.stringify({passed:true,checks,errors,synthetic_model:true,live_model_tested:false,live_google_tested:false,phone_push_tested:false},null,2));console.log(JSON.stringify({passed:true,checks}));
}catch(e){await p.screenshot({path:path.join(out,'agenda-failure.png'),fullPage:true});throw e}finally{await browser.close()}
