import {createAndSkip} from './qa-setup-helper.mjs';
// Full application/queue/HTTP adapter test using tests/browser_app.py on port 8001.
// The local model returns explicit synthetic text. No paid provider is contacted.
import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
const out=path.resolve('../research/verification');
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
const page=await context.newPage();const errors=[],checks={};page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:8001/app',{waitUntil:'networkidle'});
 await page.getByLabel('Adın',{exact:true}).fill('Sohbet testi');
 await page.getByLabel('E-posta',{exact:true}).fill(`chat-${Date.now()}@example.test`);
 await page.getByLabel('Parola',{exact:true}).fill('Local-test-'+crypto.randomUUID());
 await page.getByRole('button',{name:'Çalışma alanımı oluştur',exact:true}).click();
 const dialog=page.getByRole('dialog');await createAndSkip(page,'Test · Sohbet alanı');
 const pilot=await page.evaluate(()=>fetch('/api/test/pilot',{method:'POST'}).then(r=>r.json()));
 if(!pilot.synthetic_test_only)throw Error('Requires the isolated test app, no production grants');
 await page.getByLabel('Yapılacak iş',{exact:true}).fill('TEST: Kahve dükkanım için içerik planı hazırla.');
 await page.getByRole('button',{name:'Başlayalım',exact:true}).click();
 await expect(page).toHaveURL(/conversation=[a-f0-9]{32}/);
 await expect(page.locator('.chat-progress')).toBeVisible({timeout:10000});
 await page.screenshot({path:path.join(out,'chat-working-desktop.png'),fullPage:true});
 await expect(page.locator('.chat-answer')).toContainText('Önceki yanıt sayısı: 0',{timeout:15000});
 const firstURL=page.url();
 await page.getByLabel('Sohbet mesajı',{exact:true}).fill('TEST: Bunu üç maddeye kısalt.');
 await page.getByRole('button',{name:'Gönder',exact:true}).click();
 await expect(page.locator('.chat-answer').last()).toContainText('Önceki yanıt sayısı: 1',{timeout:15000});
 checks.followup_has_history=true;
 await page.reload({waitUntil:'networkidle'});
 await expect(page.locator('.chat-answer')).toHaveCount(2,{timeout:10000});
 await expect(page.locator('.chat-answer').last()).toContainText('TEST: Bunu üç maddeye kısalt.');
 checks.reload_preserves_conversation=true;
 await page.locator('.chat-message-tools').last().getByRole('button',{name:'Hafızaya ekle',exact:true}).click();
 await expect(dialog).toBeVisible();
 await dialog.getByLabel('Başlık',{exact:true}).fill('Test · İçerik tercihi');
 await dialog.getByLabel('Hatırlanacak bilgi',{exact:true}).fill('Bu test çalışma alanında kısa, üç maddelik içerikleri tercih ediyorum.');
 await dialog.getByRole('button',{name:'Hafızaya kaydet',exact:true}).click();
 await expect(dialog).not.toBeVisible();await expect(page.getByRole('status')).toContainText('hafızasına eklendi');
 const wid=new URL(page.url()).searchParams.get('workspace');
 const saved=await page.evaluate(wid=>fetch('/api/workspaces/'+wid+'/memories').then(r=>r.json()),wid);
 if(saved.length!==1||!saved[0].content.includes('üç maddelik'))throw Error('Memory not persisted');
 checks.explicit_memory_saved=true;
 await page.getByRole('button',{name:'Sohbet başlığını düzenle',exact:true}).click();
 await page.getByLabel('Sohbet başlığı',{exact:true}).fill('Test · Kahve içerikleri');
 await page.locator('.chat-rename').getByRole('button',{name:'Kaydet',exact:true}).click();
 await expect(page.locator('.chat-top')).toContainText('Test · Kahve içerikleri');
 await page.screenshot({path:path.join(out,'chat-desktop.png'),fullPage:true});
 const exportHref=await page.getByRole('link',{name:'Sohbeti indir',exact:true}).getAttribute('href');
 const exported=await context.request.get('http://127.0.0.1:8001'+exportHref);if(!(await exported.text()).includes('TEST: Bunu üç maddeye kısalt.'))throw Error('Export missing message');
 checks.export_contains_dialogue=true;
 await page.setViewportSize({width:390,height:844});
 await expect(page.getByLabel('Sohbet mesajı',{exact:true})).toBeVisible();
 await page.screenshot({path:path.join(out,'chat-mobile.png'),fullPage:true});
 let widths=await page.evaluate(()=>({page:document.documentElement.scrollWidth,viewport:innerWidth}));if(widths.page>widths.viewport)throw Error('Mobile overflow');
 await page.getByLabel('Sohbet mesajı',{exact:true}).fill('TEST: İptal edilecek görev.');
 await page.getByRole('button',{name:'Gönder',exact:true}).click();
 await expect(page.getByRole('button',{name:'Durdur',exact:true})).toBeVisible();await expect(page.locator('.chat-progress strong').last()).toContainText('Sonucunu hazırlıyorum',{timeout:10000});
 await page.getByRole('button',{name:'Durdur',exact:true}).click();
 await expect(page.locator('.chat-failure').last()).toContainText('İptal',{timeout:15000});
 const cancelled=await page.evaluate(()=>fetch('/api'+location.pathname.replace('/app','')+'/workspaces/'+new URLSearchParams(location.search).get('workspace')+'/conversations/'+new URLSearchParams(location.search).get('conversation')).then(r=>r.json()));const last=cancelled.turns.at(-1);if(last.status!=='cancelled'||last.output!==''||JSON.parse(last.usage).cost_in_usd_ticks!==50000)throw Error('In-flight cancellation did not preserve receipt and discard output');checks.cancel_shows_terminal_status=true;checks.in_flight_cancel_keeps_charge=true;
 await page.getByRole('button',{name:'Sohbeti arşivle',exact:true}).click();
 await expect(page.locator('.chat-archived')).toContainText('Bu sohbet arşivde.');
 await page.getByRole('button',{name:'Devam etmek için aç',exact:true}).click();
 await expect(page.getByLabel('Sohbet mesajı',{exact:true})).toBeVisible();
 checks.archive_restore=true;
 await page.setViewportSize({width:1440,height:1100});
 await page.getByRole('button',{name:'Yeni sohbet',exact:true}).click();
 await page.getByLabel('Sohbet mesajı',{exact:true}).fill('TEST: İkinci ve ayrı bir konu.');
 await page.getByRole('button',{name:'Gönder',exact:true}).click();
 await expect(page.locator('.chat-answer')).toContainText('Önceki yanıt sayısı: 0',{timeout:15000});
 if(page.url()===firstURL)throw Error('New thread reused original');
 checks.new_thread_has_no_other_history=true;
 if(errors.length)throw Error(errors.join('; '));
 await fs.writeFile(path.join(out,'chat-browser-results.json'),JSON.stringify({passed:true,checks,widths,errors,model:'synthetic local HTTP service',live_model_tested:false},null,2));
 console.log(JSON.stringify({passed:true,checks,live_model_tested:false}));
}catch(error){await page.screenshot({path:path.join(out,'chat-failure.png'),fullPage:true});console.log(JSON.stringify({dialogLabels:await page.locator('dialog label').allTextContents()}));throw error}finally{await browser.close()}
