import {createAndSkip} from './qa-setup-helper.mjs';
// Isolated end-to-end content workflow. Text and images are explicitly synthetic.
import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
const out=path.resolve('../research/verification');
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
const page=await context.newPage(),errors=[],checks={};page.on('pageerror',e=>errors.push(e.message));
const call=(url,method='GET',body)=>page.evaluate(async({url,method,body})=>{const r=await fetch('/api'+url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()}},{url,method,body});
try{
 await page.goto('http://127.0.0.1:8001/app',{waitUntil:'networkidle'});
 await page.getByLabel('Adın',{exact:true}).fill('İçerik testi');await page.getByLabel('E-posta',{exact:true}).fill(`content-${Date.now()}@example.test`);await page.getByLabel('Parola',{exact:true}).fill('Local-test-'+crypto.randomUUID());await page.getByRole('button',{name:'Çalışma alanımı oluştur',exact:true}).click();
 const dialog=page.getByRole('dialog');await createAndSkip(page,'Test · Mola Kahve');
 const wid=(await call('/workspaces')).data[0].id;const base=`/workspaces/${wid}`;
 if(!(await call('/test/pilot','POST')).data.synthetic_test_only)throw Error('Requires isolated app');
 await page.getByRole('button',{name:'İçerikler',exact:true}).click();
 await page.getByRole('button',{name:'Görseller',exact:true}).click();
 const encoded=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=64;c.height=64;const x=c.getContext('2d');x.fillStyle='#235ac8';x.fillRect(0,0,64,64);x.fillStyle='white';x.fillRect(18,18,28,28);return c.toDataURL('image/png').split(',')[1]});
 await page.locator('.media-toolbar input[type=file]').setInputFiles({name:'Test logo.png',mimeType:'image/png',buffer:Buffer.from(encoded,'base64')});
 await expect(page.locator('.media-grid article')).toHaveCount(1);checks.private_media_upload=true;
 await page.getByRole('button',{name:'Marka bilgileri',exact:true}).click();await expect(dialog).toBeVisible();
 await dialog.getByLabel('Markan ne yapıyor?',{exact:true}).fill('TEST: Mahalle kahvecisi.');
 await dialog.getByLabel('Kimlere sesleniyorsun?',{exact:true}).fill('TEST: Öğrenciler ve mahalle sakinleri.');
 await dialog.getByLabel('Nasıl konuşalım?',{exact:true}).fill('Samimi, kısa ve anlaşılır.');
 await dialog.getByLabel('Marka renkleri',{exact:true}).fill('#245AF2, #F0A247');
 await dialog.getByLabel('Logo',{exact:true}).selectOption({label:'Test logo.png'});
 await dialog.getByRole('button',{name:'Marka bilgilerini kaydet',exact:true}).click();await expect(dialog).not.toBeVisible();
 const kit=(await call(base+'/brand')).data;if(kit.revision!==1||!kit.logo_asset_id||kit.colors.length!==2)throw Error('Brand not saved');checks.brand_kit_persists=true;
 await page.getByRole('button',{name:'Haftamı hazırla',exact:true}).click();
 await expect(page.locator('.chat-answer')).toContainText('7 içerik taslağın hazır',{timeout:15000});
 await page.getByRole('button',{name:'İçerikleri aç',exact:true}).click();await expect(page.locator('.content-card')).toHaveCount(7);checks.chat_creates_seven_editable_posts=true;
 await page.locator('.content-card').first().click();await expect(dialog).toBeVisible();
 await expect(dialog.locator('.post-status-row')).toContainText('Henüz yayımlanmadı.');
 await dialog.getByRole('button',{name:'Görsel hazırla',exact:true}).click();
 await expect(dialog.locator('.studio-working')).toBeVisible({timeout:10000});
 await expect(dialog.locator('.post-preview-image')).toBeVisible({timeout:20000});
 await expect.poll(()=>dialog.locator('.post-preview-image').evaluate(img=>img.naturalWidth)).toBe(256);
 checks.image_adapter_saves_private_asset=true;
 await dialog.getByRole('button',{name:'Bu sürümü onayla',exact:true}).click();
 await expect(dialog.locator('.post-status-row .content-status')).toHaveText('Onaylı');
 await dialog.getByLabel('Gönderi metni',{exact:true}).fill('TEST: Kullanıcının düzenlediği yeni gönderi metni.');
 await dialog.getByRole('button',{name:'Taslağı kaydet',exact:true}).click();await expect(dialog.locator('.post-status-row .content-status')).toHaveText('Taslak');checks.edited_approved_post_needs_new_approval=true;
 await dialog.getByRole('button',{name:'Sürüm geçmişi',exact:true}).click();await expect(dialog.locator('.content-versions details')).toHaveCount(4);checks.revision_history_saved=true;
 await page.screenshot({path:path.join(out,'content-editor-desktop.png'),fullPage:false});
 const first=(await call(base+'/content')).data.items[0];
 await dialog.getByLabel('Gönderi metni',{exact:true}).fill('TEST: Kaydedilmemiş yerel değişiklik.');
 const keys=['title','platform','format','caption','visual_brief','planned_local','timezone','asset_id'];
 const external=Object.fromEntries(keys.map(k=>[k,first[k]]));external.caption='TEST: Başka oturumun yeni sürümü.';external.expected_revision=first.revision;
 if((await call(base+'/content/'+first.id,'PUT',external)).status!==200)throw Error('Concurrent edit setup failed');
 await expect(dialog.getByRole('button',{name:'Değişikliklerimi bırak, son sürümü aç',exact:true})).toBeVisible({timeout:10000});
 await dialog.getByRole('button',{name:'Taslağı kaydet',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Bu içerik değişti');
 const current=(await call(base+'/content/'+first.id)).data.post;if(current.caption!==external.caption)throw Error('Stale editor overwrote newer revision');checks.stale_editor_cannot_overwrite=true;
 await dialog.getByRole('button',{name:'Değişikliklerimi bırak, son sürümü aç',exact:true}).click();await expect(dialog.getByLabel('Gönderi metni',{exact:true})).toHaveValue(external.caption);
 await expect(dialog.getByRole('alert')).not.toBeVisible();
 await page.setViewportSize({width:390,height:844});await dialog.evaluate(d=>{d.scrollTop=0});await page.screenshot({path:path.join(out,'content-editor-mobile.png'),fullPage:false});
 await dialog.getByRole('button',{name:'Kapat',exact:true}).click();
 await page.getByRole('button',{name:'Haftalık takvim',exact:true}).click();await expect(page.locator('.content-week>section')).toHaveCount(7);
 await page.screenshot({path:path.join(out,'content-calendar-mobile.png'),fullPage:true});
 const widths=await page.evaluate(()=>({page:document.documentElement.scrollWidth,viewport:innerWidth}));if(widths.page>widths.viewport)throw Error('Mobile page overflow');
 checks.calendar_and_mobile_no_overflow=true;
 await page.setViewportSize({width:1440,height:1100});await page.getByRole('button',{name:'Tüm içerikler',exact:true}).click();await page.screenshot({path:path.join(out,'content-studio-desktop.png'),fullPage:true});
 const balance=(await call(base+'/billing')).data;if(balance.spent_milli!==4001||balance.held_milli!==0)throw Error('Content/image usage not reconciled');checks.text_and_image_costs_recorded=true;
 await page.reload({waitUntil:'networkidle'});await expect(page.locator('.content-card')).toHaveCount(7);checks.reload_preserves_content=true;
 if(errors.length)throw Error(errors.join('; '));
 await fs.writeFile(path.join(out,'content-browser-results.json'),JSON.stringify({passed:true,checks,widths,errors,live_model_tested:false,live_image_provider_tested:false,live_social_publishing_tested:false,model:'synthetic local HTTP text/image service'},null,2));
 console.log(JSON.stringify({passed:true,checks}));
}catch(e){await page.screenshot({path:path.join(out,'content-failure.png'),fullPage:true});throw e}finally{await browser.close()}
