import {createAndSkip} from './qa-setup-helper.mjs';
import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
const out=path.resolve('../research/verification');await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
// Capture settled responsive layouts, not a sidebar transition during resize.
const context=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce'});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
 await page.screenshot({path:path.join(out,'landing-desktop.png'),fullPage:true});
 await page.goto('http://127.0.0.1:5173/app',{waitUntil:'networkidle'});
 await page.getByLabel('Adın',{exact:true}).fill('Deneme');
 await page.getByLabel('E-posta',{exact:true}).fill(`qa-${Date.now()}@example.test`);
 await page.getByLabel('Parola',{exact:true}).fill('Local-review-'+crypto.randomUUID());
 await page.getByRole('button',{name:'Çalışma alanımı oluştur',exact:true}).click();
 const dialog=page.getByRole('dialog');await createAndSkip(page,'Örnek · Mola Kahve','business',{sector:'Örnek kahve dükkânı',tone:'Samimi, kısa ve sade. Bu bir test çalışma alanıdır.'});
 await page.getByRole('heading',{name:'Merhaba, Deneme.'}).waitFor();
 await page.getByRole('button',{name:'Hafıza',exact:true}).click();
 await page.getByRole('button',{name:'Bilgi ekle',exact:true}).click();
 await dialog.getByLabel('Başlık',{exact:true}).fill('Örnek işletme bilgisi');
 await dialog.getByLabel('İşdaşların ne bilmeli?',{exact:true}).fill('Bu yalnızca arayüz doğrulaması için eklenmiş örnek bilgidir. Gerçek müşteri veya satış verisi değildir.');
 await dialog.getByRole('button',{name:'Hafızaya kaydet',exact:true}).click();
 await page.getByRole('heading',{name:'Örnek işletme bilgisi',exact:true}).waitFor();
 await page.reload({waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Hafıza',exact:true}).click();
 await page.getByRole('heading',{name:'Örnek işletme bilgisi',exact:true}).waitFor();
 await page.screenshot({path:path.join(out,'memory-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Ajandam',exact:true}).click();
 await page.getByRole('button',{name:'Plan ekle',exact:true}).first().click();
 await dialog.getByLabel('Ne planlıyorsun?',{exact:true}).fill('Örnek içerik değerlendirmesi');
 await dialog.getByLabel('Başlangıç',{exact:true}).fill('2026-10-05T10:00');
 await dialog.getByLabel('Bitiş',{exact:true}).fill('2026-10-05T10:30');
 await dialog.getByRole('button',{name:'Ajandaya ekle',exact:true}).click();
 await page.getByRole('heading',{name:'Örnek içerik değerlendirmesi',exact:true}).waitFor();
 await page.getByRole('button',{name:'Çalışma masam',exact:true}).click();
 await page.screenshot({path:path.join(out,'workspace-desktop.png'),fullPage:true});
 const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(out,'workspace-mobile.png'),fullPage:true});
 const mobileWidth=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));
 await page.getByRole('button',{name:'Menüyü aç',exact:true}).click();
 await page.getByRole('button',{name:'Bağlantılar',exact:true}).click();
 await page.getByRole('heading',{name:'Bağlantılarını yönet.',exact:true}).waitFor();
 await page.screenshot({path:path.join(out,'connections-mobile.png'),fullPage:true});
 await fs.writeFile(path.join(out,'browser-results.json'),JSON.stringify({checked_at:new Date().toISOString(),passed:errors.length===0&&width.scroll<=width.viewport&&mobileWidth.scroll<=mobileWidth.viewport,errors,width,mobileWidth,checks:['landing loads','registration','workspace creation','memory creation','memory persists after reload','calendar creation','desktop and mobile render','connector disabled state'],live_model_tested:false},null,2));
 console.log(JSON.stringify({errors,width,mobileWidth,output:out}));
}finally{await browser.close()}
