import hashlib,json,xml.etree.ElementTree as ET
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];research=ROOT/'research';v=research/'verification'
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
suite=ET.parse(v/'tests.xml').getroot().find('testsuite');assert suite.attrib['tests']=='215' and suite.attrib['errors']=='0' and suite.attrib['failures']=='0'
archive=ROOT/'output/Isdas-Sunucu-Paketi-20261004-r9.zip';browser=read(v/'agenda-browser-results.json');deployment=read(v/'deployment-results.json');main=read(v/'agenda-main-app.json')
assert browser['passed'] and deployment['passed'] and deployment['archive']==archive.name and main['web_assets_match_release_manifest']
next_flow='Complete reviewed external content publication and scheduling for supported connectors; actual subscription payments, full voice/native app and own-server live acceptance remain. Secure provider/server and commercial configuration requests remain pending.'
evidence={'date':'2026-10-04','goal_status':'active','agenda_tests':23,'backend_tests':215,'test_suite':suite.attrib,'browser':browser,'deployment':deployment,'release':{'file':archive.name,'sha256':hashlib.sha256(archive.read_bytes()).hexdigest(),'bytes':archive.stat().st_size},'main_app':main,'screenshots_reviewed':['agenda-desktop.png','agenda-mobile.png','agenda-tablet.png','agenda-plan-mobile.png'],'live_model_tested':False,'live_google_tested':False,'phone_push_tested':False,'own_server_deployed':False,'next_product_flow':next_flow,'implemented':['shared tasks with assignee/date/priority/estimate and state lifecycle','revision-safe edits, task/event create receipts and atomic reviewed plan application','xAI prepare_agenda_plan proposal through actual worker; no autoactivation','same-thread current applied/completed plan state in follow-up context','independent durable reminder scheduler with revoked access and restore hold','exact task links and source-plan/source-conversation handoff','local calendar create/edit/delete, IANA timezone validation and existing ICS export','desktop/tablet/mobile, unsaved edit protection and lost-response retry'], 'limits':['local synthetic model proves tool/queue plumbing, not real model plan quality','Hermes does not yet implement the structured plan tool','chat cannot directly update/complete existing tasks; UI supports it','up to 20 requester open tasks and last 3 conversation plans are context excerpts','in-app reminders only; no OS push or new email','ICS exports calendar events, not tasks','5,000 total tasks per workspace','live payment, publication, phone voice/native, server and pilot remain']}
write(v/'agenda-implementation.json',evidence)
p=research/'implementation-status.json';s=read(p);s['previous_goal_turn']=s['this_goal_turn'];s['this_goal_turn']='progress: full local agenda with reviewed conversation-to-task plans, team assignments, dates/priority/time estimates, state lifecycle, conflict-safe edits and idempotent saves; independent in-app reminders, exact task and source-conversation handoff, current completed plan context, local calendar edits; 215 tests, mobile/tablet/desktop QA, r9 archive and local backup/migration verified'
extra=['../backend/agenda.py','../frontend/src/Agenda.tsx','../frontend/src/agenda.css','../tests/test_agenda.py','verification/agenda-implementation.json','verification/agenda-browser-results.json','../output/Ajanda-Planlar-ve-Hatirlatmalar-Notlari.txt']
for req in s['requirements']:
 if req['id'] in {'R04','R07','R10','R12'}:req['evidence']=list(dict.fromkeys(req.get('evidence',[])+extra))
 if req['id']=='R07':
  req['status']='memory_documents_brand_conversations_and_reviewed_agenda_tasks_implemented_locally_live_quality_pending'
  req['limit']=req.get('limit','')+' Konuşmadan önerilen planı seçerek ajandaya kaydetme, görev yaşam döngüsü, yerel takvim düzenleme, sorumluya uygulama içi hatırlatma ve güncel planla sohbete devam yerel olarak doğrulandı. Canlı model kalitesi, doğrudan sohbetten mevcut görev değiştirme ve gerçek cihaz kabulü bekliyor.'
 if req['id']=='R10':req['limit']=req.get('limit','')+' Ajanda hatırlatmaları uzun model işinden bağımsız çalışır; aynı hatırlatma çoğalmaz, işlem hatası geri alınır ve yedekten dönüş kilidinde çalışmaz.'
 if '../output/Isdas-Sunucu-Paketi-20261004-r8.zip' in req.get('evidence',[]):req['evidence']=[x.replace('Isdas-Sunucu-Paketi-20261004-r8.zip',archive.name) for x in req['evidence']]
c=s['current_verification'];c['backend_tests']=215;c['latest_release']=archive.name;c['isolated_browser_test_server']='agenda synthetic-model server stopped after acceptance; no real Google/model/SMTP writes'
c['browser_checks']+=['agenda desktop/tablet/mobile task and local-calendar create/edit','durable reminder to exact task and refresh','complete/archive/restore invalidates old reminders','plan selection/edit and committed response-loss replay without duplicates','stale task revision recovery and unsaved plan/event protection','source conversation and current applied/done plan context','plain assistant answer to editable task']
s['user_steering']['next']=next_flow;write(p,s)
p=research/'product-experience-backlog.json';s=read(p);s['current_verified_milestone']='Reviewed chat-to-agenda plans, actual shared tasks, dates/priority/assignees, durable in-app reminders and local calendar edit are verified in 215 backend tests and desktop/tablet/mobile browser flows; r9 release and local upgrade preserve earlier data. Full commercial/native/live launch remains incomplete.';s['next_product_flow']=next_flow
for row in s['acceptance']:
 if row['flow']=='Personal assistant and employee productivity':row['state']='reviewed chat-to-task plan, assignments, dates/priorities/estimates, complete/archive/restore, search/day/week filters, local event edits, in-app reminders, exact source links and current plan context implemented locally; live quality, direct chat updates, full calendar sync and more integrations remain'
 if row['flow']=='Speak or write to a finished result':row['state']='persistent text chat, real queue/status, completion notices and same-conversation continuation; typed agenda proposals become selected editable tasks with idempotent save; live model quality and full voice remain'
write(p,s);print(json.dumps({'recorded':True,'backend_tests':215,'release':archive.name,'goal_status':'active'}))
