import React,{useEffect,useState} from 'react';
import {Check,LoaderCircle,Mail,ShieldCheck} from 'lucide-react';
import {api} from './api';
import './account.css';

type Row=Record<string,any>;
function Brand(){return <a className="brand" href="/"><span className="brandmark">i<span>•</span></span>işdaş<span className="brandperiod">.</span></a>}
function Feedback({error,message}:{error:string,message:string}){return <>{error&&<div role="alert" className="error">{error}</div>}{message&&<div role="status" className="account-success">{message}</div>}</>}

export function Auth({onDone,invitationToken='',invitationEmail='',invitationNotice=''}:{onDone:(r:Row)=>void,invitationToken?:string,invitationEmail?:string,invitationNotice?:string}){
 const[register,setRegister]=useState(new URLSearchParams(location.search).get('login')!=='1'),[options,setOptions]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/auth/options').then(r=>{setOptions(r);if(!r.registration_enabled&&!invitationToken)setRegister(false)}).catch(e=>setError(e.message))},[]);
 return <div className="auth-page"><Brand/><div className="auth-grid"><div className="auth-story"><div className="eyebrow">HER İŞİN BİR İŞDAŞI VAR</div><h1>İşlerin çoksa,<br/>yalnız değilsin.</h1><img src="/mascot.png" alt="Piko"/><p>Bir çalışma alanı aç.<br/>İlk işini birlikte halledelim.</p></div><section className="auth-card"><span className="pill">İŞDAŞ'A HOŞ GELDİN</span><h2>{register?'Birlikte başlayalım.':'Yeniden merhaba.'}</h2><p>{invitationNotice||(register?'Kendi çalışma alanın seni bekliyor.':'İşlerinin kaldığı yere dön.')}</p>{options&&!options.registration_enabled&&!invitationToken&&<p>Yeni kayıtlar şu anda kapalı. Mevcut hesabınla giriş yapabilirsin.</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const d=Object.fromEntries(new FormData(e.currentTarget));try{onDone(await api('/auth/'+(register?'register':'login'),'POST',{...d,...(register&&invitationToken?{invitation_token:invitationToken}:{})}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{register&&<label>Adın<input name="name" autoComplete="name" required maxLength={80}/></label>}<label>E-posta<input name="email" type="email" autoComplete="email" required maxLength={254} defaultValue={invitationEmail} readOnly={!!invitationEmail}/></label><label>Parola<input name="password" type="password" autoComplete={register?'new-password':'current-password'} minLength={10} maxLength={128} required placeholder="En az 10 karakter"/></label><Feedback error={error} message=""/><button className="button" disabled={busy||!options}>{busy&&<LoaderCircle className="spin" size={18}/>} {register?'Çalışma alanımı oluştur':'Oturum aç'}</button></form><div className="account-links">{(options?.registration_enabled||!!invitationToken)&&<button className="text-link" onClick={()=>{setRegister(!register);setError('')}}>{register?'Zaten hesabım var':'Yeni hesap oluştur'}</button>}<a className="text-link" href="/account/forgot">Parolamı unuttum</a></div></section></div></div>
}

function Verification({onRefresh}:{onRefresh:()=>Promise<void>}){
 const[account,setAccount]=useState<Row|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;const refresh=()=>api('/account').then(r=>{if(live)setAccount(r)}).catch(e=>{if(live)setError(e.message)});refresh();const timer=setInterval(refresh,5000);return()=>{live=false;clearInterval(timer)}},[]);
 const states:Record<string,string>={queued:'E-posta gönderim sırasında.',sending:'E-posta gönderiliyor.',sent:'E-posta sunucusu iletiyi kabul etti. Gelen kutunu ve spam klasörünü kontrol et.',uncertain:'Gönderim doğrulanamadı. E-posta gelmediyse yeni bağlantı iste.',expired:'Bağlantının süresi doldu. Yeni bağlantı iste.',cancelled:'Önceki bağlantı kapatıldı.'};
 return <div className="account-verification"><span className="role-icon blue">{account?.email_verified?<ShieldCheck/>:<Mail/>}</span><div><h3>{account?.email_verified?'E-posta adresin doğrulandı':'E-posta adresini doğrula'}</h3><p>{account?.email||'Hesabın yükleniyor…'}</p>{account&&!account.email_verified&&<><p>Gelen bağlantıyı açıp hesabının parolasıyla doğrula. Bağlantı 24 saat geçerlidir.</p>{!account.mail_available?<p>E-posta hizmeti henüz hazır değil. Lütfen daha sonra yeniden dene.</p>:<p>{states[account.verification_delivery?.state]||'Doğrulama bağlantısı isteyebilirsin.'}</p>}</>}<Feedback error={error} message={message}/><div className="button-row">{account&&!account.email_verified&&<button className="button secondary" disabled={busy||!account.mail_available} onClick={async()=>{setBusy(true);setError('');setMessage('');try{const r=await api('/account/send-verification','POST');setMessage(r.message);setAccount(await api('/account'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Yeni bağlantı gönder</button>}<button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setAccount(await api('/account'));await onRefresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Doğrulamayı kontrol et</button></div></div></div>
}

export function VerificationGate({onRefresh,onLogout}:{onRefresh:()=>Promise<void>,onLogout:()=>Promise<void>}){return <div className="account-page"><Brand/><section className="account-card"><span className="eyebrow">SON BİR ADIM</span><h1>Bu hesabın sana ait olduğunu doğrulayalım.</h1><Verification onRefresh={onRefresh}/><button className="text-link" onClick={onLogout}>Başka hesapla giriş yap</button></section></div>}

function PasswordFields(){return <><label>Yeni parola<input type="password" name="password" autoComplete="new-password" minLength={10} maxLength={128} placeholder="En az 10 karakter" required/></label><label>Yeni parola tekrar<input type="password" name="confirm_password" autoComplete="new-password" minLength={10} maxLength={128} required/></label></>}

export function AccountSettings({onRefresh,onLogout}:{onRefresh:()=>Promise<void>,onLogout:()=>void}){
 const[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="account-settings"><div><span className="eyebrow">HESABIN SENİN KONTROLÜNDE</span><h1>Hesabım</h1><p>E-posta doğrulamanı ve parolanı buradan yönet.</p></div><section className="panel"><Verification onRefresh={onRefresh}/></section><section className="panel"><h2>Parolamı değiştir</h2><p>Değişiklikten sonra tüm cihazlardaki oturumların kapanır. Yeni parolanla tekrar giriş yaparsın.</p><form onSubmit={async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));setError('');if(d.password!==d.confirm_password){setError('Yeni parolalar aynı olmalı.');return}setBusy(true);try{await api('/account/change-password','POST',{...d});onLogout()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Mevcut parola<input name="current_password" type="password" autoComplete="current-password" minLength={10} maxLength={128} required/></label><PasswordFields/><Feedback error={error} message=""/><button className="button" disabled={busy}>{busy&&<LoaderCircle className="spin" size={18}/>}Parolayı değiştir ve çıkış yap</button></form></section></div>
}

// Capture once before rendering: StrictMode may mount components twice. Tokens
// stay in memory only, never in localStorage, query strings or later navigation.
const route=location.pathname.split('/').filter(Boolean)[1];
const accountToken=location.pathname.startsWith('/account/')?new URLSearchParams(location.hash.slice(1)).get('token')||'':'';
if(location.pathname.startsWith('/account/')&&location.hash)history.replaceState(null,'',location.pathname);

function RecoveryPage(){
 const[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[options,setOptions]=useState<Row|null>(null),[token,setToken]=useState(accountToken);
 useEffect(()=>{api('/auth/options').then(setOptions).catch(e=>setError(e.message))},[]);
 useEffect(()=>{const capture=()=>{setToken(new URLSearchParams(location.hash.slice(1)).get('token')||'');history.replaceState(null,'',location.pathname);setDone(false);setError('');setMessage('')};addEventListener('hashchange',capture);return()=>removeEventListener('hashchange',capture)},[]);
 const forgot=route==='forgot',verify=route==='verify',reset=route==='reset',valid=forgot||((verify||reset)&&!!token);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));setError('');setMessage('');if(reset&&d.password!==d.confirm_password){setError('Yeni parolalar aynı olmalı.');return}setBusy(true);try{const r=await api('/auth/'+(forgot?'forgot-password':verify?'verify-email':'reset-password'),'POST',forgot?d:{...d,token});setMessage(forgot?r.message:verify?'E-posta adresin doğrulandı. Çalışma alanına devam edebilirsin.':'Parolan yenilendi ve önceki oturumların kapatıldı. Yeni parolanla giriş yapabilirsin.');if(!forgot)setDone(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="account-page"><Brand/><section className="account-card"><span className="role-icon blue">{done?<Check/>:<ShieldCheck/>}</span><h1>{forgot?'Parolanı yenileyelim.':verify?'E-posta adresini doğrula.':'Yeni parolanı belirle.'}</h1>{!valid?<><p>Bu bağlantı eksik veya geçersiz. Yeni bir bağlantı iste.</p><a className="button" href="/account/forgot">Parola yenileme bağlantısı iste</a></>:<><p>{forgot?'Hesabında kullandığın e-posta adresini yaz.':verify?'Doğrulamayı tamamlamak için İşdaş hesabının parolasını gir.':'Yeni parolan en az 10 karakter olmalı. Diğer oturumların da kapanacak.'}</p>{!done&&<form onSubmit={submit}>{forgot?<label>E-posta<input type="email" name="email" autoComplete="email" maxLength={254} required/></label>:verify?<label>Hesabının parolası<input type="password" name="password" autoComplete="current-password" minLength={10} maxLength={128} required/></label>:<PasswordFields/>}{forgot&&options&&!options.mail_available&&<p>E-posta hizmeti henüz hazır değil. Lütfen daha sonra yeniden dene.</p>}<button className="button" disabled={busy||(forgot&&(!options||!options.mail_available))}>{busy&&<LoaderCircle className="spin" size={18}/>} {forgot?'Bağlantı gönder':verify?'E-posta adresimi doğrula':'Yeni parolayı kaydet'}</button></form>}<Feedback error={error} message={message}/></>}<div className="account-links"><a className="text-link" href={done&&verify?'/app':'/app?login=1'}>{done&&verify?'Çalışma alanına dön':'Giriş sayfasına dön'}</a>{verify&&!done&&<a className="text-link" href="/account/forgot">Parolamı bilmiyorum</a>}</div></section></div>
}

function InvitationPage(){
 const[token,setToken]=useState(accountToken),[preview,setPreview]=useState<Row|null>(null),[user,setUser]=useState<Row|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const capture=()=>{setToken(new URLSearchParams(location.hash.slice(1)).get('token')||'');history.replaceState(null,'',location.pathname);setPreview(null);setError('')};addEventListener('hashchange',capture);return()=>removeEventListener('hashchange',capture)},[]);
 useEffect(()=>{let alive=true;api('/me').then(r=>{if(alive)setUser(r)}).catch(()=>{}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[]);
 useEffect(()=>{let alive=true;if(token)api('/invitations/preview','POST',{token}).then(r=>{if(alive)setPreview(r)}).catch(e=>{if(alive)setError(e.message)});else setError('Davet bağlantısı eksik. E-postadaki bağlantıyı yeniden aç.');return()=>{alive=false}},[token]);
 if(loading)return <div className="loading"><LoaderCircle className="spin"/></div>;
 if(preview&&!user)return <Auth key={token} invitationToken={token} invitationEmail={preview.email} invitationNotice={`${preview.workspace_name} alanına ${preview.role==='reviewer'?'müşteri':'ekip üyesi'} olarak davetlisin. Katılmak için bu e-posta adresiyle giriş yap veya hesap oluştur.`} onDone={setUser}/>;
 if(preview&&user&&user.email===preview.email&&!user.email_verified)return <><p className="invitation-notice">Davet sekmesini açık tut. E-posta adresini doğruladıktan sonra buradan devam edebilirsin.</p><VerificationGate onRefresh={async()=>setUser(await api('/me'))} onLogout={async()=>{await api('/auth/logout','POST');setUser(null)}}/></>;
 return <div className="account-page"><Brand/><section className="account-card"><span className="role-icon blue"><Mail/></span><h1>{preview?preview.workspace_name+' seni bekliyor.':'Çalışma alanı daveti'}</h1>{preview&&<><p>{preview.email} adresi için {preview.role==='reviewer'?'müşteri':'ekip üyesi'} daveti.</p><p>{preview.role==='reviewer'?'Yalnızca sana gönderilen içerikleri görebilir, yorumlayabilir ve onaylayabilirsin.':'Bu alanın ortak sohbetlerini, belgelerini, hafızasını ve içeriklerini görebilir; ekip çalışmalarına katılabilirsin.'}</p>{user?.email!==preview.email?<><p>Şu anda {user?.email} hesabındasın. Davet edilen adresle giriş yapmalısın.</p><button className="button" onClick={async()=>{await api('/auth/logout','POST');setUser(null)}}>Doğru hesapla giriş yap</button></>:<button className="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await api('/invitations/accept','POST',{token});location.assign(`/app?workspace=${r.workspace_id}&view=${r.role==='reviewer'?'reviews':'home'}`)}catch(e){setError((e as Error).message);setBusy(false)}}}>Daveti kabul et</button>}</>}<Feedback error={error} message=""/><div className="account-links"><a className="text-link" href="/app">Uygulamaya dön</a></div></section></div>
}

export function AccountPage(){return route==='invite'?<InvitationPage/>:<RecoveryPage/>}
