import {useEffect,useRef,useState} from 'react';
import {Archive,Bell,CalendarDays,Check,ChevronLeft,ChevronRight,Clock3,Download,Flag,LoaderCircle,Plus,RefreshCw,Search,Sparkles,X} from 'lucide-react';
import {api} from './api';
import {JobAllowance} from './Billing';
import './agenda.css';
type Row=Record<string,any>;
const labels:Row={high:'Öncelikli',normal:'Normal',low:'Esnek'};
const taskBody=(r:Row)=>Object.fromEntries(['title','notes','due_local','timezone','priority','estimate_minutes','remind_before','assignee_id'].map(k=>[k,r[k]]));
const dayIn=(zone:string)=>new Intl.DateTimeFormat('sv-SE',{timeZone:zone}).format(new Date());
const moveDay=(day:string,n:number)=>{const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const localTime=(iso:string,zone:string)=>{const p=Object.fromEntries(new Intl.DateTimeFormat('sv-SE',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso)).map(v=>[v.type,v.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`};
const dueLabel=(row:Row,zone:string)=>row.due_at?new Date(row.due_at*1000).toLocaleString('tr-TR',{timeZone:zone,day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Tarih seçilmedi';
function Dialog({title,children,onClose}:{title:string,children:React.ReactNode,onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null),previous=useRef<HTMLElement|null>(null);useEffect(()=>{previous.current=document.activeElement as HTMLElement;ref.current?.showModal();return()=>{ref.current?.close();previous.current?.focus()}},[]);return <dialog className="agenda-dialog" ref={ref} aria-label={title} onCancel={e=>{e.preventDefault();onClose()}}><div className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label="Kapat" onClick={onClose}><X size={20}/></button></div>{children}</dialog>}

export function Agenda({wid,timezone,ready,focusTask,focusPlan,draftFocus,onFocusClosed,onPlan}:{wid:string,timezone:string,ready:boolean,focusTask?:string,focusPlan?:string,draftFocus?:Row,onFocusClosed:()=>void,onPlan:(prompt:string)=>Promise<void>}){
 const [day,setDay]=useState(dayIn(timezone)),[scope,setScope]=useState('today'),[mine,setMine]=useState(false),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0),[data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[task,setTask]=useState(''),[plan,setPlan]=useState(''),[draft,setDraft]=useState<Row|undefined>(),[event,setEvent]=useState<Row|null>(null),[showPrompt,setShowPrompt]=useState(false),[prompt,setPrompt]=useState(''),[allPlans,setAllPlans]=useState(false);
 const alive=useRef(true),seq=useRef(0);const base=`/workspaces/${wid}/agenda`;
 async function load(){const s=++seq.current;try{const r=await api(base+'?'+new URLSearchParams({day,scope,mine:String(mine),q:query,offset:String(page*50)}));if(alive.current&&s===seq.current){setData(r);setError('')}}catch(e){if(alive.current&&s===seq.current){setData(null);setError((e as Error).message)}}}
 useEffect(()=>{alive.current=true;setData(null);load();const t=setInterval(()=>{if(document.visibilityState==='visible')load()},7000);return()=>{alive.current=false;seq.current++;clearInterval(t)}},[wid,day,scope,mine,query,page]);
 useEffect(()=>{if(focusTask){setTask(focusTask);setPlan('')}else if(focusPlan){setPlan(focusPlan);setTask('')}else if(draftFocus){setDraft(draftFocus);setTask('new')}},[focusTask,focusPlan,draftFocus]);
 function close(){setTask('');setPlan('');setDraft(undefined);onFocusClosed()}
 async function state(row:Row,action:string){if(busy)return;setBusy(row.id);try{await api(base+'/tasks/'+row.id+'/state','POST',{action,expected_revision:row.revision});if(alive.current){setNotice(action==='done'?'Bir işi daha tamamladın.':action==='archive'?'İş arşive alındı.':'İşin durumu güncellendi.');await load()}}catch(e){if(alive.current)setError((e as Error).message)}finally{if(alive.current)setBusy('')}}
 return <div className="agenda"><div className="page-title"><div><span className="eyebrow">AKLINDA TUTMA, BİRLİKTE TAKİP EDELİM</span><h1>Ajandam</h1><p>Yapılacaklarını sırala, zamanını ayır, bitenleri geride bırak.</p></div><button className="button" onClick={()=>{setDraft(undefined);setTask('new')}}><Plus size={18}/>Yapılacak ekle</button></div>
  {error&&<div className="error" role="alert">{error}<button className="text-link" onClick={load}>Yeniden yükle</button></div>}{notice&&<div className="agenda-notice" role="status"><Check size={17}/>{notice}<button className="icon-button" aria-label="Bilgiyi kapat" onClick={()=>setNotice('')}><X size={16}/></button></div>}
  <div className="agenda-day"><div className="agenda-day-picker"><button className="icon-button" aria-label="Önceki gün" onClick={()=>{setDay(moveDay(day,-1));setPage(0)}}><ChevronLeft/></button><label><span>Günün</span><input aria-label="Ajanda günü" type="date" value={day} onChange={e=>{if(e.target.value){setDay(e.target.value);setPage(0)}}}/></label><button className="icon-button" aria-label="Sonraki gün" onClick={()=>{setDay(moveDay(day,1));setPage(0)}}><ChevronRight/></button><button className="text-link" onClick={()=>{setDay(dayIn(timezone));setPage(0)}}>Bugün</button></div><span className="agenda-zone"><Clock3 size={15}/>{timezone}</span></div>
  <div className="agenda-summary"><div><span className="role-icon blue"><CalendarDays size={21}/></span><p>Bu güne kalan<strong>{data?data.summary.due_by:'—'}</strong></p></div><div><span className="role-icon orange"><Flag size={21}/></span><p>Geciken<strong>{data?.summary.overdue??'—'}</strong></p></div><div><span className="role-icon violet"><Clock3 size={21}/></span><p>Tarihi olmayan<strong>{data?.summary.undated??'—'}</strong></p></div></div>
  <section className="agenda-planner"><img src="/mascot.png" alt=""/><div><h2>Gününü birlikte toparlayalım.</h2><p>İşlerini anlat. Piko ile Ada düzenlenebilir bir plan hazırlasın.</p></div><button className="button secondary" onClick={()=>setShowPrompt(!showPrompt)}><Sparkles size={17}/>{showPrompt?'Plan isteğini kapat':'Birlikte planlayalım'}</button>{showPrompt&&<form onSubmit={async e=>{e.preventDefault();setBusy('plan');setError('');try{await onPlan(prompt+'\nAjandada seçtiğim gün: '+day+'. Saat dilimim: '+timezone+'. Düzenlenebilir bir yapılacaklar planı hazırla.')}catch(e){if(alive.current)setError((e as Error).message)}finally{if(alive.current)setBusy('')}}}><label>Bugün neleri halletmek istiyorsun?<textarea aria-label="Planlanacak işler" value={prompt} onChange={e=>setPrompt(e.target.value)} required maxLength={12000} placeholder="Örneğin: Sunumumu hazırlamam, müşteri teklifini kontrol etmem ve haftalık içeriği planlamam gerekiyor. Önceliklerine göre sırala."/></label><JobAllowance wid={wid} agent="assistant"/>{!ready&&<p className="muted">Asistan bağlantısı hazırlanıyor. Bu sırada işlerini kendin ekleyebilirsin.</p>}<button className="button" disabled={!!busy||!ready||!prompt.trim()}>{busy==='plan'?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>}Planımı hazırla</button></form>}</section>
  {!!data?.plans.length&&<section className="agenda-proposals"><div className="section-heading"><div><h2>İncelemen için planlar</h2><p>Seçip kaydetmeden yapılacaklarına eklenmez.</p></div>{data.plans.length>3&&<button className="text-link" onClick={()=>setAllPlans(!allPlans)}>{allPlans?'Daha az göster':`Planları göster (${data.plans.length})`}</button>}</div>{data.plans.slice(0,allPlans?20:3).map((p:Row)=><button className="agenda-plan-card" key={p.id} onClick={()=>setPlan(p.id)}><Sparkles size={20}/><span><strong>{p.title}</strong><small>{p.items.length} öneri · Henüz ajandaya eklenmedi</small></span><ChevronRight size={18}/></button>)}</section>}
  <div className="agenda-columns"><section className="panel agenda-tasks"><div className="section-heading"><h2>Yapılacaklar</h2><label className="agenda-mine"><input type="checkbox" checked={mine} onChange={e=>{setMine(e.target.checked);setPage(0)}}/>Bana ait</label></div><div className="agenda-tabs" role="group" aria-label="Yapılacak filtresi">{[['today','Günüm'],['week','7 gün'],['all','Tümü'],['done','Bitenler'],['archived','Arşiv']].map(([key,label])=><button key={key} aria-pressed={scope===key} className={scope===key?'active':''} onClick={()=>{setScope(key);setPage(0)}}>{label}</button>)}</div><form className="agenda-search" onSubmit={e=>{e.preventDefault();setQuery(search);setPage(0)}}><Search size={17}/><input aria-label="Yapılacaklarda ara" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Bir işi bul" maxLength={100}/><button className="text-link">Ara</button>{query&&<button className="icon-button" type="button" aria-label="Aramayı temizle" onClick={()=>{setSearch('');setQuery('');setPage(0)}}><X size={16}/></button>}</form>{['today','week'].includes(scope)&&<p className="agenda-list-note">Geciken ve tarihi olmayan işler de bu listede.</p>}
   {!data&&!error&&<div className="agenda-empty" role="status"><LoaderCircle className="spin"/><p>Ajandan açılıyor.</p></div>}
   {data?.items.map((t:Row)=><article className={'agenda-task '+t.status} key={t.id}><button className={'agenda-check '+(t.status==='done'?'checked':'')} aria-label={t.title+(t.status==='open'?' işini tamamla':t.status==='done'?' işini yeniden aç':' işini arşivden çıkar')} disabled={!!busy} onClick={()=>state(t,t.status==='open'?'done':t.status==='done'?'reopen':'restore')}>{busy===t.id?<LoaderCircle size={16} className="spin"/>:t.status==='done'?<Check size={17}/>:t.status==='archived'?<RefreshCw size={15}/>:null}</button><button className="agenda-task-open" onClick={()=>setTask(t.id)}><strong>{t.title}</strong><span className="agenda-task-meta"><span className={t.status==='open'&&t.due_at&&t.due_at<Date.now()/1000?'late':''}>{dueLabel(t,timezone)}</span>{t.estimate_minutes&&<span>{t.estimate_minutes} dk</span>}{t.remind_before!==null&&<span title="Uygulama içi hatırlatma"><Bell size={13}/></span>}</span><small>{t.assignee_name}</small></button><span className={'agenda-priority '+t.priority}>{labels[t.priority]}</span>{t.status!=='archived'&&<button className="icon-button" aria-label={t.title+' işini arşivle'} disabled={!!busy} onClick={()=>state(t,'archive')}><Archive size={16}/></button>}</article>)}
   {data&&!data.items.length&&<div className="agenda-empty"><Check size={27}/><h3>{scope==='done'?'Biten işler burada birikecek.':query?'Bu aramada iş bulunamadı.':'Biraz alan açıldı.'}</h3><p>{query?'Başka bir kelimeyle arayabilir veya aramayı temizleyebilirsin.':'Yeni bir iş ekleyebilir ya da gününü birlikte planlayabilirsin.'}</p></div>}
   {data&&(page>0||data.next_offset!==null)&&<div className="agenda-pages"><button className="button secondary small" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Önceki</button><span>{page+1}. sayfa</span><button className="button secondary small" disabled={data.next_offset===null} onClick={()=>setPage(p=>p+1)}>Sonraki</button></div>}
  </section><aside><section className="panel agenda-events"><div className="section-heading"><h2>Günün takvimi</h2><button className="icon-button" aria-label="Takvime zaman ayır" onClick={()=>setEvent({id:'new'})}><Plus size={20}/></button></div><p className="muted">Toplantıların ve ayırdığın zamanlar.</p>{data?.events.map((e:Row)=><button className="agenda-event" key={e.id} onClick={()=>setEvent(e)}><span>{new Date(e.starts_at).toLocaleTimeString('tr-TR',{timeZone:timezone,hour:'2-digit',minute:'2-digit'})}</span><div><strong>{e.title}</strong><small>{Math.round((new Date(e.ends_at).getTime()-new Date(e.starts_at).getTime())/60000)} dakika</small></div></button>)}{data&&!data.events.length&&<div className="agenda-event-empty"><CalendarDays size={28}/><p>Bu güne henüz zaman ayırmadın.</p></div>}<button className="button secondary" onClick={()=>setEvent({id:'new'})}><Plus size={16}/>Zaman ayır</button><a className="text-link" href={`/api/workspaces/${wid}/events.ics`}><Download size={15}/>Takvimi indir</a></section><div className="agenda-hint"><Bell size={19}/><p>Hatırlatmalar bu uygulamanın bildirim paneline gelir. Telefonuna kapalı uygulama bildirimi gönderilmez.</p></div><p className="agenda-sharing">Ajanda bu alanın ekip üyeleriyle paylaşılır. Kişisel işlerin için kendine ait bir alan kullanabilirsin.</p></aside></div>
  {task&&<TaskEditor key={task} wid={wid} id={task} timezone={timezone} initial={draft} members={data?.members||[]} selfId={data?.self_id||''} onClose={close} onSaved={async()=>{await load();setNotice('Yapılacak iş kaydedildi.')}}/>}
  {plan&&<PlanReview key={plan} wid={wid} id={plan} members={data?.members||[]} selfId={data?.self_id||''} onClose={close} onSaved={load} onTask={id=>{setPlan('');setTask(id);onFocusClosed()}}/>}
  {event&&<EventEditor key={event.id} wid={wid} event={event} timezone={timezone} day={day} onClose={()=>setEvent(null)} onSaved={async()=>{await load();setNotice('Takvim güncellendi.')}}/>}
 </div>;
}

function TaskFields({value:v,onChange,members}:{value:Row,onChange:(v:Row)=>void,members:Row[]}){const put=(k:string,x:any)=>onChange({...v,[k]:x,...(k==='due_local'&&!x?{remind_before:null}:{})});return <div className="agenda-fields"><label>Yapılacak iş<input aria-label="Yapılacak işin adı" value={v.title} onChange={e=>put('title',e.target.value)} required maxLength={200}/></label><label>Notlar<textarea aria-label="İşin notları" value={v.notes} onChange={e=>put('notes',e.target.value)} maxLength={5000}/></label><div className="form-grid"><label>Tarih ve saat <small>İsteğe bağlı</small><input aria-label="İşin tarihi" type="datetime-local" value={v.due_local||''} onChange={e=>put('due_local',e.target.value||null)}/></label><label>Saat dilimi<input aria-label="İşin saat dilimi" value={v.timezone} onChange={e=>put('timezone',e.target.value)} required maxLength={80}/></label></div><div className="form-grid"><label>Öncelik<select aria-label="İşin önceliği" value={v.priority} onChange={e=>put('priority',e.target.value)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{String(label)}</option>)}</select></label><label>Tahmini süre <small>Dakika</small><input aria-label="İşin tahmini süresi" type="number" min={5} max={1440} value={v.estimate_minutes??''} onChange={e=>put('estimate_minutes',e.target.value?Number(e.target.value):null)}/></label></div><div className="form-grid"><label>Sorumlu<select aria-label="İşin sorumlusu" value={v.assignee_id||''} onChange={e=>put('assignee_id',e.target.value||null)}><option value="">Ben</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}{v.assignee_id&&!members.some(m=>m.id===v.assignee_id)&&<option value={v.assignee_id}>Alan dışındaki kişi · Yeniden seç</option>}</select></label><label>Hatırlatma<select aria-label="İşin hatırlatması" disabled={!v.due_local} value={v.remind_before??''} onChange={e=>put('remind_before',e.target.value===''?null:Number(e.target.value))}><option value="">Hatırlatma yok</option>{[[0,'Tam zamanında'],[5,'5 dakika önce'],[15,'15 dakika önce'],[30,'30 dakika önce'],[60,'1 saat önce'],[1440,'1 gün önce']].map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div></div>}

function TaskEditor({wid,id,timezone,initial,members,selfId,onClose,onSaved}:{wid:string,id:string,timezone:string,initial?:Row,members:Row[],selfId:string,onClose:()=>void,onSaved:()=>Promise<void>}){
 const [value,setValue]=useState<Row>({title:'',notes:'',due_local:null,timezone,priority:'normal',estimate_minutes:null,remind_before:null,assignee_id:selfId||null,...initial}),[row,setRow]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false);
 const alive=useRef(true),attempt=useRef<{signature:string,key:string}|null>(null);const base=`/workspaces/${wid}/agenda/tasks`;
 async function load(){const r=await api(base+'/'+encodeURIComponent(id));if(alive.current){setRow(r);setValue(taskBody(r));setDirty(false);setError('')}}
 useEffect(()=>{alive.current=true;if(id!=='new')load().catch(e=>alive.current&&setError(e.message));return()=>{alive.current=false}},[wid,id]);
 function close(){if(busy)return;if(dirty)setDiscard(true);else onClose()}
 return <Dialog title={id==='new'?'Yeni yapılacak iş':'İşin ayrıntıları'} onClose={close}>{error&&<p className="error" role="alert">{error}{id!=='new'&&<button className="text-link" onClick={()=>load().catch(e=>setError(e.message))}>Değişikliklerimi bırak, son sürümü aç</button>}</p>}{id!=='new'&&!row&&!error?<p>İş açılıyor.</p>:(id==='new'||row)&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const body=taskBody(value),signature=JSON.stringify(body);if(attempt.current?.signature!==signature)attempt.current={signature,key:crypto.randomUUID()};try{await api(base+(id==='new'?'':'/'+id),id==='new'?'POST':'PUT',{...body,...(id==='new'?{request_key:attempt.current.key}:{expected_revision:row!.revision})});if(!alive.current)return;setDirty(false);await onSaved();onClose()}catch(e){if(alive.current)setError((e as Error).message)}finally{if(alive.current)setBusy(false)}}}><fieldset disabled={busy||row?.status==='archived'}><TaskFields value={value} members={members} onChange={v=>{setValue(v);setDirty(true)}}/><p className="agenda-sharing">Bu alanın ekip üyeleri bu işi görebilir ve düzenleyebilir. Hatırlatma yalnızca sorumlu kişiye gider.</p><button className="button" disabled={id!=='new'&&!dirty}><Check size={17}/>{id==='new'?'Ajandama ekle':'Değişiklikleri kaydet'}</button></fieldset>{row?.status==='archived'&&<p>İşi arşivden çıkardıktan sonra düzenleyebilirsin.</p>}</form>}{!dirty&&row?.plan_id&&<a className="text-link agenda-source-link" href={'/app?'+new URLSearchParams({workspace:wid,view:'calendar',plan:row.plan_id})}>Kaynak planı aç</a>}{discard&&<div className="agenda-discard" role="alert"><p>Kaydetmediğin değişiklikler var.</p><button className="button secondary" onClick={()=>setDiscard(false)}>Düzenlemeye dön</button><button className="text-link" onClick={onClose}>Kaydetmeden kapat</button></div>}</Dialog>
}

function PlanReview({wid,id,members,selfId,onClose,onSaved,onTask}:{wid:string,id:string,members:Row[],selfId:string,onClose:()=>void,onSaved:()=>Promise<void>,onTask:(id:string)=>void}){
 const [plan,setPlan]=useState<Row|null>(null),[items,setItems]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false);const alive=useRef(true);const base=`/workspaces/${wid}/agenda/plans/${encodeURIComponent(id)}`;
 useEffect(()=>{alive.current=true;api(base).then(r=>{if(alive.current){setPlan(r);setItems(r.items.map((item:Row)=>({...item,assignee_id:selfId||null,selected:true})))}}).catch(e=>alive.current&&setError(e.message));return()=>{alive.current=false}},[wid,id]);
 const count=items.filter(v=>v.selected).length;
 return <Dialog title="Planını birlikte netleştirelim." onClose={()=>{if(!busy){if(dirty&&!plan?.applied_at)setDiscard(true);else onClose()}}}>{error&&<p className="error" role="alert">{error}</p>}{!plan&&!error?<p>Plan açılıyor.</p>:plan?.applied_at?<div className="agenda-applied"><span className="role-icon green"><Check/></span><h3>Bu plan ajandaya eklendi.</h3><p>İşlerin son durumunu açıp düzenleyebilirsin.</p>{plan.task_ids.map((tid:string,i:number)=><button key={tid} className="button secondary" onClick={()=>onTask(tid)}>{i+1}. işi aç<ChevronRight size={17}/></button>)}</div>:plan&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await api(base+'/apply','POST',{items:items.filter(v=>v.selected).map(taskBody)});if(alive.current){setPlan(result.plan);setDirty(false);await onSaved()}}catch(e){if(alive.current)setError((e as Error).message)}finally{if(alive.current)setBusy(false)}}}><p className="agenda-plan-title">{plan.title}</p><p className="muted">İşleri, tarihleri ve hatırlatmaları kontrol et. Yalnızca seçtiğin işler kaydedilecek.</p><fieldset disabled={busy}>{items.map((item,i)=><section className={'agenda-plan-item '+(!item.selected?'excluded':'')} key={i}><label className="agenda-plan-select"><input type="checkbox" aria-label={`${i+1}. işi plana dahil et`} checked={item.selected} onChange={e=>{setDirty(true);setItems(old=>old.map((v,n)=>n===i?{...v,selected:e.target.checked}:v))}}/>{i+1}. iş</label><details open={i===0}><summary>{item.title}</summary><fieldset disabled={!item.selected}><TaskFields value={item} members={members} onChange={value=>{setDirty(true);setItems(old=>old.map((v,n)=>n===i?value:v))}}/></fieldset></details></section>)}<button className="button" disabled={!count}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}Seçtiğim {count} işi ajandama ekle</button></fieldset><p className="agenda-sharing">Bu kayıtlar Google Takvim'e veya başka bir hesaba gönderilmez.</p></form>}{!dirty&&plan?.conversation_id&&<a className="text-link agenda-source-link" href={'/app?'+new URLSearchParams({workspace:wid,view:'chat',conversation:plan.conversation_id})}>Sohbette devam et</a>}{discard&&<div className="agenda-discard" role="alert"><p>Plan değişikliklerin henüz kaydedilmedi.</p><button className="button secondary" onClick={()=>setDiscard(false)}>Düzenlemeye dön</button><button className="text-link" onClick={onClose}>Kaydetmeden kapat</button></div>}</Dialog>
}

function EventEditor({wid,event,timezone,day,onClose,onSaved}:{wid:string,event:Row,timezone:string,day:string,onClose:()=>void,onSaved:()=>Promise<void>}){
 const fresh=event.id==='new';const [value,setValue]=useState<Row>({title:event.title||'',notes:event.notes||'',starts_local:fresh?day+'T09:00':localTime(event.starts_at,timezone),ends_local:fresh?day+'T10:00':localTime(event.ends_at,timezone),timezone,expected_revision:event.revision||null}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[remove,setRemove]=useState(false),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false);
 const attempt=useRef({key:crypto.randomUUID(),signature:''});
 const put=(k:string,v:string)=>{setDirty(true);setValue(old=>({...old,[k]:v}))};
 return <Dialog title={fresh?'Takviminde zaman ayır':'Takvim kaydını düzenle'} onClose={()=>{if(!busy){if(dirty)setDiscard(true);else onClose()}}}>{error&&<p role="alert" className="error">{error}</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const signature=JSON.stringify(value);if(attempt.current.signature&&attempt.current.signature!==signature)attempt.current.key=crypto.randomUUID();attempt.current.signature=signature;await api(`/workspaces/${wid}/agenda/events`+(fresh?'':'/'+event.id),fresh?'POST':'PUT',{...value,request_key:attempt.current.key});await onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy}><label>Başlık<input aria-label="Takvim başlığı" value={value.title} onChange={e=>put('title',e.target.value)} required maxLength={200}/></label><div className="form-grid"><label>Başlangıç<input aria-label="Takvim başlangıcı" type="datetime-local" value={value.starts_local} onChange={e=>put('starts_local',e.target.value)} required/></label><label>Bitiş<input aria-label="Takvim bitişi" type="datetime-local" value={value.ends_local} onChange={e=>put('ends_local',e.target.value)} required/></label></div><label>Saat dilimi<input value={value.timezone} onChange={e=>put('timezone',e.target.value)} required/></label><label>Not<textarea value={value.notes} onChange={e=>put('notes',e.target.value)} maxLength={5000}/></label><p className="agenda-sharing">Bu alanın yerel takvimine kaydedilir. Katılımcı daveti göndermez; hatırlatma için bir yapılacak iş oluşturabilirsin.</p><div className="button-row"><button className="button">{fresh?'Zamanı ayır':'Kaydet'}</button>{!fresh&&<button type="button" className="text-link" onClick={()=>setRemove(true)}>Takvimden kaldır</button>}</div></fieldset></form>{remove&&<div className="agenda-discard" role="alert"><p>Bu takvim kaydı kaldırılsın mı?</p><button className="button danger" disabled={busy} onClick={async()=>{setBusy(true);try{await api(`/workspaces/${wid}/agenda/events/${event.id}?expected_revision=${event.revision}`,'DELETE');await onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Evet, kaldır</button><button className="button secondary" onClick={()=>setRemove(false)}>Vazgeç</button></div>}{discard&&<div className="agenda-discard" role="alert"><p>Takvim değişikliklerin henüz kaydedilmedi.</p><button className="button secondary" onClick={()=>setDiscard(false)}>Düzenlemeye dön</button><button className="text-link" onClick={onClose}>Kaydetmeden kapat</button></div>}</Dialog>
}
