import {useEffect,useRef,useState} from 'react';
import {BookOpen,Download,FileText,LoaderCircle,Search,Trash2,Upload,X} from 'lucide-react';
import {api} from './api';
import './Knowledge.css';
type Row=Record<string,any>;
const size=(n:number)=>n>1024*1024?(n/1024/1024).toFixed(1)+' MB':Math.ceil(n/1024)+' KB';

export function KnowledgeLibrary({wid,owner}:{wid:string,owner:boolean}){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[results,setResults]=useState<Row[]|null>(null),[searching,setSearching]=useState(false);
 const alive=useRef(true),searchSequence=useRef(0),loadSequence=useRef(0);const base=`/workspaces/${wid}`;
 async function load(){const seq=++loadSequence.current;const r=await api(base+'/documents');if(alive.current&&seq===loadSequence.current)setData(r)}
 useEffect(()=>{alive.current=true;load().catch(e=>setError(e.message));return()=>{alive.current=false;searchSequence.current++;loadSequence.current++}},[wid]);
 return <section className="knowledge-library panel"><div className="knowledge-heading"><div><span className="eyebrow">DOSYALARINDAN BİLGİYE</span><h2>Belgelerin</h2><p>Dosyanı ekle. İşdaşın soruna uygun bölümleri bulsun.</p></div><label className="button secondary upload"><Upload size={17}/>{busy?'Belge okunuyor…':'Belge yükle'}<input aria-label="Belge yükle" type="file" accept=".pdf,.docx,.txt,.csv,.md" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const response=await fetch('/api'+base+'/documents',{method:'POST',body:form,credentials:'include'});const r=await response.json();if(!response.ok)throw Error(typeof r.detail==='string'?r.detail:'Belge yüklenemedi.');if(!alive.current)return;await load();setResults(null);setSelected(r.id)}catch(e){if(alive.current)setError((e as Error).message)}finally{if(alive.current)setBusy(false)}}}/></label></div>
 <p className="knowledge-help">PDF, Word (.docx), TXT, CSV ve Markdown · Dosya başına 8 MB. Taranmış görseller okunmaz. Belgeler bu alanın üyeleriyle paylaşılır.</p>
 {error&&<p className="error" role="alert">{error}</p>}{busy&&<p className="knowledge-working" role="status"><LoaderCircle className="spin" size={17}/>Metin ve bölümler hazırlanıyor. Bu işlem biraz sürebilir.</p>}
 <form className="knowledge-search" onSubmit={async e=>{e.preventDefault();const seq=++searchSequence.current;setSearching(true);setError('');try{const r=await api(base+'/document-search?q='+encodeURIComponent(query));if(alive.current&&seq===searchSequence.current)setResults(r.items)}catch(e){if(alive.current&&seq===searchSequence.current)setError((e as Error).message)}finally{if(alive.current&&seq===searchSequence.current)setSearching(false)}}}><input aria-label="Belgelerde ara" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Örneğin: iade süresi" minLength={2} maxLength={500}/><button className="button secondary" disabled={searching||query.trim().length<2}><Search size={17}/>Ara</button></form>
 {results!==null&&<div className="knowledge-results"><div><strong>{results.length?'İlgili bölümler':'Eşleşen bölüm bulunamadı.'}</strong><button className="text-link" onClick={()=>{searchSequence.current++;setResults(null);setSearching(false)}}>Aramayı kapat</button></div>{!results.length&&<p>Belgedeki kelimelerle tekrar dene. Arama açık belgelerin metninde yapılır.</p>}{results.map(r=><button className="knowledge-hit" key={r.chunk_id} onClick={()=>setSelected(r.document_id)}><strong>{r.name}</strong><small>{r.label}</small><p>{r.body}</p></button>)}</div>}
 <div className="document-grid">{data?.items.map((d:Row)=><button className={'document-card '+(!d.enabled?'inactive':'')} key={d.id} onClick={()=>setSelected(d.id)}><FileText size={22}/><span><strong>{d.name}</strong><small>{d.kind.toUpperCase()} · {size(d.bytes)} · {d.characters.toLocaleString('tr-TR')} karakter</small><span className="document-status">{d.enabled?'İşdaşların kullanabilir':'Kullanıma kapalı'}</span></span></button>)}</div>
 {data&&!data.items.length&&<p className="knowledge-empty">Ürün kataloğun, çalışma notların veya işletme bilgilerinle başlayabilirsin.</p>}
 {data&&<small className="knowledge-meter">{data.items.length} / {data.document_limit} belge · {size(data.bytes)} / {size(data.limit_bytes)}</small>}
 {selected&&<DocumentDetail key={selected} wid={wid} did={selected} owner={owner} onClose={()=>setSelected('')} onChanged={async()=>{await load();setResults(null)}}/>}
 </section>
}

function DocumentDetail({wid,did,owner,onClose,onChanged}:{wid:string,did:string,owner:boolean,onClose:()=>void,onChanged:()=>Promise<void>}){
 const ref=useRef<HTMLDialogElement>(null),alive=useRef(true);const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[remove,setRemove]=useState(false);
 const url=`/workspaces/${wid}/documents/${did}`;
 async function load(offset=0){const r=await api(url+(offset?'?offset='+offset:''));if(alive.current)setData(old=>({...r,chunks:offset?[...(old?.chunks||[]),...r.chunks]:r.chunks}))}
 useEffect(()=>{alive.current=true;ref.current?.showModal();load().catch(e=>setError(e.message));return()=>{alive.current=false;ref.current?.close()}},[wid,did]);
 const d=data?.document;
 return <dialog className="document-dialog" aria-label="Belge ayrıntıları" ref={ref} onCancel={onClose}><div className="modal-head"><h2>{d?.name||'Belge açılıyor…'}</h2><button className="icon-button" aria-label="Kapat" onClick={onClose}><X size={20}/></button></div>{error&&<p className="error" role="alert">{error}</p>}{d&&<><div className="document-actions"><a className="button secondary" href={'/api'+url+'/download'}><Download size={16}/>Özgün dosyayı indir</a>{owner&&<button className="icon-button" aria-label="Belgeyi kaldır" onClick={()=>setRemove(true)}><Trash2 size={18}/></button>}</div>{owner&&<label className="document-toggle"><input type="checkbox" checked={!!d.enabled} disabled={busy} onChange={async e=>{const enabled=e.target.checked;setBusy(true);setError('');setData(old=>old?{...old,document:{...old.document,enabled}}:old);try{await api(url,'PATCH',{enabled});await load();await onChanged()}catch(e){if(alive.current){setData(old=>old?{...old,document:{...old.document,enabled:!enabled}}:old);setError((e as Error).message)}}finally{if(alive.current)setBusy(false)}}}/>İşdaşlarım yeni yanıtlarda kullanabilsin</label>}
 {remove&&<div className="document-remove"><strong>Belge kaldırılsın mı?</strong><p>Dosya ve okunmuş bölümleri kaldırılır. Önceki sohbet yanıtları silinmez. Devam eden bir iş bu belgeyi kullanıyorsa sonucu kaydedilmez.</p><div className="button-row"><button className="button danger" disabled={busy} onClick={async()=>{setBusy(true);try{await api(url,'DELETE');await onChanged();onClose()}catch(e){if(alive.current){setError((e as Error).message);setBusy(false)}}}}>Evet, belgeyi kaldır</button><button className="button secondary" onClick={()=>setRemove(false)}>Vazgeç</button></div></div>}
 {d.warnings.map((w:string)=><p className="document-warning" key={w}>{w}</p>)}<h3>Okunan bölümler</h3><p className="knowledge-help">Asistan, soruna göre bu bölümlerden seçer. Önemli sayı ve tabloları özgün dosyayla karşılaştırabilirsin.</p><div className="document-sections">{data?.chunks.map((c:Row)=><article key={c.ordinal}><strong>{c.label}</strong><p>{c.body}</p></article>)}</div>{data?.next_offset!==null&&<button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await load(data.next_offset)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Diğer bölümleri göster</button>}</>}</dialog>
}

export function DocumentPicker({wid,value,onChange}:{wid:string,value:string[],onChange:(ids:string[])=>void}){
 const [items,setItems]=useState<Row[]>([]),[error,setError]=useState('');useEffect(()=>{let live=true;api(`/workspaces/${wid}/documents`).then(r=>live&&setItems(r.items)).catch(e=>live&&setError(e.message));return()=>{live=false}},[wid]);
 if(!items.length&&!value.length&&!error)return null;
 return <details className="document-picker"><summary><BookOpen size={16}/>Belge seç {value.length?`(${value.length})`:'(isteğe bağlı)'}</summary><p>En fazla 5 belge seç. Seçmezsen alanındaki açık belgelerde ilgili bölümler aranır. Uzun belgelerin tamamı her yanıta alınmaz.</p>{error&&<p className="error" role="alert">{error}</p>}{items.map(d=><label key={d.id}><input type="checkbox" checked={value.includes(d.id)} disabled={!value.includes(d.id)&&(!d.enabled||value.length>=5)} onChange={e=>onChange(e.target.checked?[...value,d.id]:value.filter(id=>id!==d.id))}/><span>{d.name}{!d.enabled?' · kullanıma kapalı':''}</span></label>)}{value.some(id=>!items.some(d=>d.id===id))&&<p>Önceden seçilmiş bir belge artık listede değil.</p>}{value.length>0&&<button type="button" className="text-link" onClick={()=>onChange([])}>Belge seçimini temizle</button>}</details>
}

export function DocumentSources({wid,jid,count}:{wid:string,jid:string,count:number}){
 const [open,setOpen]=useState(false),[data,setData]=useState<Row|null>(null),[error,setError]=useState('');useEffect(()=>{if(!open)return;let live=true;api(`/workspaces/${wid}/jobs/${jid}/documents`).then(r=>live&&setData(r)).catch(e=>live&&setError(e.message));return()=>{live=false}},[wid,jid,open]);
 if(!count)return null;
 return <div className="document-sources"><button className="text-link" onClick={()=>setOpen(!open)}><BookOpen size={15}/>{open?'Belge bölümlerini kapat':`Belge bölümleri (${count})`}</button>{open&&<div>{error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p>Bölümler açılıyor…</p>}{data&&<><p className="knowledge-help">{data.note}</p>{data.items.map((s:Row)=><details key={s.code}><summary>[{s.code}] {s.name} · {s.label}</summary>{s.available?<><p>{s.body}</p><a href={`/api/workspaces/${wid}/documents/${s.document_id}/download`} className="text-link">Özgün dosyayı indir</a>{!s.enabled&&<small>Bu belge artık yeni yanıtlarda kullanılmıyor.</small>}</>:<p>Belge kaldırıldı. Önceki yanıt metni sohbet geçmişinde korunuyor.</p>}</details>)}</>}</div>}</div>
}
