import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,Compass,Globe,LoaderCircle,MessageCircle,Plug,Search,Shield,Store,UserRound,Users,X} from 'lucide-react';
import {api} from './api';
import type {SetupIntent} from './setupIntent';
import {KnowledgeLibrary} from './Knowledge';
import {JobAllowance} from './Billing';
import './Onboarding.css';
type Row=Record<string,any>;
const personas=[{id:'personal',title:'Kendim için',detail:'Günümü düzenleyeyim, araştırayım, işlerimi yetiştireyim.',icon:UserRound,note:'Sana göre bir çalışma arkadaşı.'},{id:'business',title:'İşletmem için',detail:'Markamı tanısın; içerik, araştırma ve müşteri yanıtı hazırlasın.',icon:Store,note:'İşini bilen küçük bir ekip.'},{id:'agency',title:'Ajansım için',detail:'Her müşterinin işi ayrı dursun; ekibimle hazırlayıp onaya sunayım.',icon:Users,note:'Her marka için ayrı bir masa.'}];
const goals=[['planning','Günümü düzenlemek'],['content','İçerik hazırlamak'],['research','Araştırma yapmak'],['sales','Satışa hazırlanmak'],['support','Müşteri yanıtları'],['documents','Belgelerle çalışmak']];
const steps=[['profile','Seni tanıyalım'],['knowledge','Bilgilerini ekle'],['connections','Araçlarını bağla'],['first_task','İlk işine başla']];
const brandKeys=['description','audience','offerings','tone','avoid','visual_style','colors','logo_asset_id'];
function Shell({step,children,onExit,exitLabel='Çalışma alanıma dön',name}:{step:number,children:React.ReactNode,onExit?:()=>void,exitLabel?:string,name?:string}){
 return <div className="setup-shell"><header className="setup-header"><a href="/" className="brand"><span className="brandmark">i<span>•</span></span>işdaş<span className="brandperiod">.</span></a><span className="setup-header-note">Birlikte başlayalım.</span>{onExit&&<button className="text-link" onClick={onExit}>{exitLabel}<X size={16}/></button>}</header><div className="setup-layout"><aside className="setup-story"><span className="eyebrow">MERHABA, BEN PİKO.</span><h1>{step===0?<>Biraz sen.<br/>Biraz işin.<br/><em>Sonrası birlikte.</em></>:<>Her şey<br/><em>sana göre.</em></>}</h1><p>{name?`${name} için küçük bir hazırlık yapalım. Bilgilerini daha sonra da değiştirebilirsin.`:'Ne yapmak istediğini seç. Sana uygun işdaşlarla, kendi çalışma alanını hazırlayalım.'}</p><div className="setup-piko"><span>{step===4?'İlk işi birlikte seçelim.':'Seni tanımakla başlayalım.'}</span><img src="/mascot.png" alt="Mavi kuş rehberin Piko"/></div><div className="setup-assurance"><Shield size={18}/><span>Her çalışma alanının hafızası ayrıdır. Eklediğin bilgileri görebilir, düzenleyebilir ve silebilirsin.</span></div></aside><main className="setup-main">{step>0&&<ol className="setup-progress" aria-label="Başlangıç adımları">{steps.map(([id,label],i)=><li key={id} aria-current={step===i+1?'step':undefined} className={step===i+1?'current':step>i+1?'passed':''}><span>{step>i+1?<Check size={15}/>:i+1}</span><small>{label}</small></li>)}</ol>}{children}</main></div></div>;
}
export function CreateWorkspace({onCreated,onExit,exitLabel,initialIntent}:{onCreated:(id:string)=>Promise<void>,onExit:()=>void,exitLabel?:string,initialIntent?:SetupIntent|null}){
 const [kind,setKind]=useState<string>(initialIntent?.kind||'business'),[name,setName]=useState(''),[sector,setSector]=useState(''),[website,setWebsite]=useState(''),[goal,setGoal]=useState(initialIntent?.goal||'content'),[timezone,setTimezone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Istanbul'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const attempt=useRef<{signature:string,key:string}|null>(null),alive=useRef(true),locked=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 return <Shell step={0} onExit={onExit} exitLabel={exitLabel}><div className="setup-heading"><span className="eyebrow">SEN NEREDEN BAŞLAMAK İSTERSİN?</span><h2>İşdaş'ı nasıl kullanacaksın?</h2><p>Her alanın kendi bilgileri, sohbetleri ve işleri var.</p></div><form onSubmit={async e=>{e.preventDefault();if(locked.current)return;locked.current=true;setBusy(true);setError('');const values={name:name.trim(),kind,sector,website:website.trim(),goal,timezone};const signature=JSON.stringify(values);if(attempt.current?.signature!==signature)attempt.current={signature,key:crypto.randomUUID()};try{const r=await api('/workspace-setup','POST',{...values,idempotency_key:attempt.current.key});if(alive.current)await onCreated(r.workspace_id)}catch(e){if(alive.current)setError((e as Error).message)}finally{locked.current=false;if(alive.current)setBusy(false)}}}><fieldset className="setup-fieldset" disabled={busy}><legend className="sr-only">Kullanım amacı</legend><div className="persona-options">{personas.map(p=><label className={'persona-option '+(kind===p.id?'selected':'')} key={p.id}><input type="radio" name="persona" value={p.id} checked={kind===p.id} onChange={()=>{setKind(p.id);setGoal(p.id==='personal'?'planning':'content')}}/><p.icon size={24}/><span><strong>{p.title}</strong><small>{p.detail}</small></span><span className="persona-check">{kind===p.id&&<Check size={14}/>}</span></label>)}</div><div className="setup-fields"><label>Çalışma alanının adı<input value={name} onChange={e=>setName(e.target.value)} required maxLength={100} placeholder={kind==='personal'?'Örneğin: Benim çalışma masam':kind==='agency'?'Örneğin: Mola · Müşteri alanı':'Örneğin: Mola Kahve'}/></label><label>{kind==='personal'?'İşin veya ilgi alanın':'İşin veya sektörün'} <small>İsteğe bağlı</small><input value={sector} onChange={e=>setSector(e.target.value)} maxLength={200} placeholder={kind==='personal'?'Örneğin: Tasarımcıyım, dil öğreniyorum':'Örneğin: Mahalle kahvecisi'}/></label><label>İlk olarak neye yardım edelim?<select value={goal} onChange={e=>setGoal(e.target.value)}>{goals.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Web siten <small>İsteğe bağlı · Bir sonraki adımda okuyabilirsin.</small><input type="url" value={website} onChange={e=>setWebsite(e.target.value)} maxLength={1000} placeholder="https://"/></label><details className="setup-details"><summary>Saat dilimi: {timezone}</summary><label>Ajandanın saat dilimi<input value={timezone} onChange={e=>setTimezone(e.target.value)} required maxLength={80} placeholder="Europe/Istanbul"/></label></details></div></fieldset>{error&&<p className="error" role="alert">{error}</p>}<div className="setup-actions"><span>Bağlantıları ve belgeleri sonra da ekleyebilirsin.</span><button className="button" disabled={busy||!name.trim()}>{busy?<LoaderCircle className="spin" size={18}/>:<ArrowRight size={18}/>}Alanımı hazırlayalım</button></div></form></Shell>;
}
const tasks:Record<string,{agent:string,title:string,prompt:string}[]>={
 planning:[{agent:'assistant',title:'Haftamı toparla',prompt:'Beni tanıdığın bilgilere göre bu hafta için uygulanabilir bir çalışma planı hazırlayalım. Önce en önemli işlerimi, son tarihlerini ve ayırabileceğim zamanı sor.'},{agent:'assistant',title:'Toplantıya hazırlan',prompt:'Yaklaşan bir toplantı için gündem ve hazırlık listesi oluşturalım. Önce toplantının amacını, katılımcıları ve beklenen kararı sor.'}],
 content:[{agent:'social',title:'Bir haftalık içerik planı',prompt:'Marka kitimi kullanarak bir haftalık Instagram içerik planı hazırla. Her gönderi için metin ve görsel tarifi öner; tarih veya kampanya bilgisi eksikse önce sor. Yayınlama yapma.'},{agent:'guide',title:'Kendimi iyi anlatayım',prompt:'Profil bilgilerime göre kısa bir tanıtım yazısı hazırlayalım. Önce nerede kullanılacağını ve kime sesleneceğimi sor; doğrulanmamış başarı veya rakam ekleme.'}],
 research:[{agent:'research',title:'Seçenekleri karşılaştır',prompt:'Bir karar için seçenekleri kaynaklarıyla karşılaştıralım. Önce konuyu, seçenekleri ve benim için önemli ölçütleri sor. Doğrulanamayan bilgileri açıkça belirt.'},{agent:'research',title:'Bir konuyu öğren',prompt:'Yeni bir konuyu anlamak istiyorum. Önce konuyu ve mevcut bilgimi sor; sonra kaynaklı, anlaşılır bir açıklama ve küçük bir öğrenme planı hazırla.'}],
 sales:[{agent:'sales',title:'Satış görüşmesine hazırlan',prompt:'İşletme bilgilerimi kullanarak bir satış görüşmesine hazırlanalım. Önce müşteriyi ve ihtiyacını sor. Değer önerisi, sorular ve görüşme akışı hazırla; e-posta gönderme.'},{agent:'guide',title:'Teklif taslağı hazırla',prompt:'Bir müşteri için teklif taslağı hazırlayalım. Kapsamı, fiyatı ve teslim tarihini benden öğren; bilmediğin koşulları uydurma.'}],
 support:[{agent:'support',title:'Bir müşteriye yanıt hazırla',prompt:'Müşterime yardımcı olacak kısa bir yanıt hazırlayalım. Önce müşterinin mesajını sor; belgelerimde olmayan iade veya garanti koşullarını uydurma. Yanıtı taslak olarak ver.'},{agent:'support',title:'Sık sorulan soruları derle',prompt:'İşletme bilgilerime ve belgelerime göre sık sorulan sorular hazırlayalım. Eksik politika bilgilerini önce sor, yanıtları kısa tut.'}],
 documents:[{agent:'guide',title:'Belgemden özet çıkar',prompt:'Yüklediğim belgelerle çalışmak istiyorum. Önce hangi belgeyi ve ne amaçla özetleyeceğimizi sor. Kaynak bölümlerini belirt; belgem yoksa yüklememi iste.'},{agent:'assistant',title:'Notları iş listesine çevir',prompt:'Çalışma notlarımı uygulanabilir bir iş listesine çevirelim. Önce notlarımı iste; sorumlu ve tarih belirtilmediyse bunları tahmin etme.'}]
};
export function WorkspaceGuide({workspace,onDone,onExit}:{workspace:Row,onDone:(target?:{view:string,cid?:string})=>Promise<void>,onExit:()=>void}){
 const wid=workspace.id,base=`/workspaces/${wid}`;
 const [data,setData]=useState<Row|null>(null),[draft,setDraft]=useState<Row|null>(null),[connections,setConnections]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[quote,setQuote]=useState<Row|null>(null),[choice,setChoice]=useState(0),[prompt,setPrompt]=useState(''),[recovered,setRecovered]=useState<Row|null>(null);
 const alive=useRef(true),locked=useRef(false),heading=useRef<HTMLHeadingElement>(null);
 async function load(){const [r,c]=await Promise.all([api(base+'/onboarding'),api(base+'/connections')]);if(alive.current){setData(r);setDraft(r.brand);setConnections(c);if(r.first_job)setRecovered(r.first_job)}}
 useEffect(()=>{alive.current=true;load().catch(e=>alive.current&&setError(e.message));return()=>{alive.current=false}},[wid]);
 const step=data?.step==='complete'?'profile':data?.step;
 const options=tasks[data?.goal||'content'];
 useEffect(()=>{setChoice(0);setPrompt(options[0].prompt)},[data?.goal]);
 useEffect(()=>{heading.current?.focus();window.scrollTo(0,0)},[step]);
 async function perform(fn:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(true);setError('');setNote('');try{await fn()}catch(e){if(alive.current)setError((e as Error).message)}finally{locked.current=false;if(alive.current)setBusy(false)}}
 async function advance(next:string){await api(base+'/onboarding','PUT',{step:next,goal:data!.goal,expected_revision:data!.revision});if(alive.current)await load()}
 async function finish(target?:{view:string,cid?:string}){await api(base+'/onboarding','PUT',{step:'complete',goal:data!.goal,expected_revision:data!.revision});if(alive.current)await onDone(target)}
 async function start(){let job=recovered||data?.first_job;if(!job){try{job=await api(base+'/jobs','POST',{prompt,agent_id:options[choice].agent,start_conversation:true,idempotency_key:`setup:${wid}:${data!.attempt_key}`})}catch(e){const latest=await api(base+'/onboarding').catch(()=>null);if(latest?.first_job){if(alive.current)setRecovered(latest.first_job);throw Error('İlk işin kaydedilmiş. Yeni bir iş başlatmadan konuşmanı açabilirsin.')}throw e}if(alive.current)setRecovered(job)}await finish({view:'chat',cid:job.conversation_id})}
 return <Shell step={Math.max(1,steps.findIndex(([id])=>id===step)+1)} name={workspace.name} onExit={busy?undefined:onExit}>
 {!data?<div className="setup-loading">{error?<><p className="error" role="alert">{error}</p><button className="button secondary" onClick={()=>perform(load)}>Yeniden dene</button></>:<><LoaderCircle className="spin"/> Bilgilerin hazırlanıyor.</>}</div>:<>
 <div className="setup-heading"><span className="eyebrow">{personas.find(p=>p.id===workspace.kind)?.note}</span><h2 ref={heading} tabIndex={-1}>{step==='profile'?(workspace.kind==='personal'?'Nasıl çalışmayı seversin?':'İşini senden öğrenelim.'):step==='knowledge'?'Bildiklerini bize de anlat.':step==='connections'?'Kullandığın araçlarla yan yana.':'İlk olarak neyi halledelim?'}</h2><p>{step==='profile'?'Kısa birkaç cümle yeter. İşdaşların hazırlarken bu bilgileri kullansın.':step==='knowledge'?'Bir dosya, web sayfası veya kısa not ekleyebilirsin. Bu adımı geçmek de mümkün.':step==='connections'?'Bir hesabı yalnızca ihtiyacın olduğunda bağla. Erişimi daha sonra kaldırabilirsin.':'Bir öneri seç, istediğin gibi değiştir ve başlayalım.'}</p></div>
 {error&&<div className="error" role="alert">{error}<button className="text-link" disabled={busy} onClick={()=>perform(load)}>Son durumu yükle</button></div>}{note&&<p className="setup-success" role="status"><Check size={17}/>{note}</p>}
 {step==='profile'&&draft&&<form onSubmit={e=>{e.preventDefault();perform(async()=>{const brand=Object.fromEntries(brandKeys.map(k=>[k,draft[k]]));await api(base+'/onboarding/profile','PUT',{...brand,expected_revision:data.revision,expected_brand_revision:draft.revision});if(alive.current)await load()})}}><fieldset className="setup-fieldset" disabled={busy}><legend className="sr-only">Profil bilgileri</legend><label>{workspace.kind==='personal'?'Kendini ve yaptığın işi kısaca anlat':'İşletmen ne yapıyor?'}<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} maxLength={3000} placeholder={workspace.kind==='personal'?'Örneğin: Tasarımcıyım. Müşteri işlerimi ve öğrenmek istediklerimi birlikte planlamak istiyorum.':'Örneğin: İzmir’de küçük bir kahve dükkânıyız. Günlük kahve ve ev yapımı tatlılar sunuyoruz.'}/></label><label>{workspace.kind==='personal'?'Kimin için çalışıyorsun?':'Kimlere hitap ediyorsun?'}<input value={draft.audience} onChange={e=>setDraft({...draft,audience:e.target.value})} maxLength={2000} placeholder="Örneğin: Yerel müşteriler, ekibim, öğrenciler…"/></label><label>{workspace.kind==='personal'?'Önemli hedeflerin veya sorumlulukların':'Ürünlerin veya hizmetlerin'}<textarea value={draft.offerings} onChange={e=>setDraft({...draft,offerings:e.target.value})} maxLength={4000} placeholder="Bilmemizi istediğin birkaç ayrıntı."/></label><label>Nasıl bir dil kullanalım?<input value={draft.tone} onChange={e=>setDraft({...draft,tone:e.target.value})} maxLength={3000} placeholder="Örneğin: Samimi, kısa ve anlaşılır."/></label><details className="setup-details"><summary>Dikkat edilmesini istediğin şeyler</summary><label>Neleri yapmayalım?<textarea value={draft.avoid} onChange={e=>setDraft({...draft,avoid:e.target.value})} maxLength={2000} placeholder="Örneğin: Abartılı vaatler ve uzun cümleler kullanma."/></label></details></fieldset><div className="setup-actions"><button type="button" className="text-link" disabled={busy} onClick={()=>perform(()=>advance('knowledge'))}>Şimdilik geç</button><button className="button" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<ArrowRight size={18}/>}Kaydet ve devam et</button></div></form>}
 {step==='knowledge'&&<><SiteKnowledge wid={wid} website={workspace.website||''}/><KnowledgeLibrary wid={wid} owner/><QuickNote wid={wid}/><div className="setup-actions"><button className="text-link" disabled={busy} onClick={()=>perform(()=>advance('profile'))}><ArrowLeft size={16}/>Geri</button><button className="button" disabled={busy} onClick={()=>perform(()=>advance('connections'))}>Bağlantılara geç<ArrowRight size={18}/></button></div></>}
 {step==='connections'&&<><div className="setup-connections">{connections.map(c=><article className={'setup-connection '+(c.connected?'connected':'')} key={c.id}><div className="connection-logo">{c.name[0]}</div><div><h3>{c.name}</h3><p>{c.description}</p><small>{c.connected?c.account:c.available?'Bağlamaya hazır':'Kurulum tamamlanınca açılacak'}</small></div><button className="button secondary" disabled={busy||c.connected||!c.available} onClick={()=>perform(async()=>{const r=await api(base+'/connections/'+c.id+'/start','POST');if(alive.current)location.assign(r.url)})}>{c.connected?<Check size={16}/>:<Plug size={16}/>} {c.connected?'Bağlı':c.available?'Bağla':'Henüz etkin değil'}</button></article>)}</div><div className="setup-tip"><Compass size={20}/><p>İçerik taslağı hazırlamak için sosyal hesabını bağlaman gerekmez. Yayınlama, ilgili bağlantı etkinleştiğinde ayrıca açılır.</p></div><div className="setup-actions"><button className="text-link" disabled={busy} onClick={()=>perform(()=>advance('knowledge'))}><ArrowLeft size={16}/>Geri</button><button className="button" disabled={busy} onClick={()=>perform(()=>advance('first_task'))}>İlk işimi seçeyim<ArrowRight size={18}/></button></div></>}
 {step==='first_task'&&<><div className="setup-ready-summary"><span><BookOpen size={17}/>{data.documents} belge</span><span><MessageCircle size={17}/>{data.memories} hafıza kaydı</span><span><Plug size={17}/>{connections.filter(c=>c.connected).length} bağlantı</span></div>{(recovered||data.first_job)?<section className="setup-resume"><Check size={24}/><h3>İlk işin kayıtlı.</h3><p>{(recovered||data.first_job).prompt}</p><p>Konuşmanı açarak durumunu görebilir ve devam edebilirsin.</p><button className="button" disabled={busy} onClick={()=>perform(start)}>Konuşmamı aç<ArrowRight size={18}/></button></section>:<><label className="setup-goal-label">Önce ne yapalım?<select value={data.goal} disabled={busy} onChange={e=>{const goal=e.target.value;perform(async()=>{await api(base+'/onboarding','PUT',{step:'first_task',expected_revision:data.revision,goal});if(alive.current)await load()})}}>{goals.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className="setup-task-options">{options.map((t,i)=><button key={t.title} className={choice===i?'selected':''} disabled={busy} aria-pressed={choice===i} onClick={()=>{setChoice(i);setPrompt(t.prompt)}}><Search size={20}/><strong>{t.title}</strong>{choice===i&&<Check size={16}/>}</button>)}</div><form onSubmit={e=>{e.preventDefault();perform(start)}}><label>İşdaşına ne söylemek istersin?<textarea className="setup-first-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} required minLength={3} maxLength={12000} disabled={busy}/></label><JobAllowance wid={wid} agent={options[choice].agent} onQuote={setQuote}/><button className="button setup-start" disabled={busy||prompt.trim().length<3||!quote?.allowed}>{busy?<LoaderCircle className="spin" size={18}/>:<ArrowRight size={18}/>}İlk işimi başlat</button></form></>}<div className="setup-actions"><button className="text-link" disabled={busy} onClick={()=>perform(()=>advance('connections'))}><ArrowLeft size={16}/>Geri</button><button className="text-link" disabled={busy} onClick={()=>perform(()=>finish())}>Şimdilik çalışma alanıma geç</button></div></>}
 </>}
 </Shell>;
}
function SiteKnowledge({wid,website}:{wid:string,website:string}){
 const [url,setUrl]=useState(website),[preview,setPreview]=useState<Row|null>(null),[title,setTitle]=useState(''),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 const alive=useRef(true),locked=useRef(false);useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 async function run(fn:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{await fn()}catch(e){if(alive.current)setError((e as Error).message)}finally{locked.current=false;if(alive.current)setBusy(false)}}
 return <section className="setup-site panel"><div className="setup-block-title"><Globe size={23}/><div><h3>Web sitenden başlayalım.</h3><p>Bir sayfanın metnini oku, incele ve seçtiğin bilgileri hafızaya ekle.</p></div></div><form className="setup-site-form" onSubmit={e=>{e.preventDefault();run(async()=>{const r=await api(`/workspaces/${wid}/site-preview`,'POST',{url:url.trim()});if(alive.current){setPreview(r);setTitle((r.title||'Web sitesi bilgileri').slice(0,100));setText(r.text);setSaved(false)}})}}><input aria-label="Okunacak web sayfası" type="url" placeholder="https://" value={url} onChange={e=>setUrl(e.target.value)} required maxLength={2000} disabled={busy}/><button className="button secondary" disabled={busy||!url.trim()}>{busy?<LoaderCircle className="spin" size={17}/>:<Globe size={17}/>}Sayfayı oku</button></form>{error&&<p className="error" role="alert">{error}</p>}{preview&&<div className="setup-site-preview"><a href={preview.url} target="_blank" rel="noreferrer">{preview.url}</a>{preview.warnings.map((s:string)=><p className="muted" key={s}>{s}</p>)}{saved?<p className="setup-success" role="status"><Check size={17}/>Hafızaya eklendi. Hafıza bölümünden düzenleyebilirsin.</p>:<form onSubmit={e=>{e.preventDefault();run(async()=>{await api(`/workspaces/${wid}/site-preview/apply`,'POST',{preview_id:preview.id,title,text});if(alive.current)setSaved(true)})}}><label>Hafızada görünecek başlık<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} required disabled={busy}/></label><label>Eklenecek bilgiler <small>Yanlış, eski veya gereksiz kısımları çıkarabilirsin.</small><textarea value={text} onChange={e=>setText(e.target.value)} minLength={40} maxLength={15000} required disabled={busy}/></label><button className="button" disabled={busy||text.trim().length<40||!title.trim()}><Check size={17}/>Bu bilgileri hafızaya ekle</button></form>}</div>}</section>;
}
function QuickNote({wid}:{wid:string}){
 const [title,setTitle]=useState(''),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);const alive=useRef(true),locked=useRef(false);useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 return <details className="setup-quick-note"><summary><MessageCircle size={19}/>Kısa bir bilgi ekle</summary><p>Örneğin çalışma saatlerin, tercihlerin veya ürün bilgilerin.</p>{error&&<p className="error" role="alert">{error}</p>}{saved?<p className="setup-success" role="status"><Check size={17}/>Bilgin hafızaya eklendi.</p>:<form onSubmit={async e=>{e.preventDefault();if(locked.current)return;locked.current=true;setBusy(true);setError('');try{await api(`/workspaces/${wid}/memories`,'POST',{title,content:text});if(alive.current)setSaved(true)}catch(e){if(alive.current)setError((e as Error).message)}finally{locked.current=false;if(alive.current)setBusy(false)}}}><label>Bilginin başlığı<input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={100}/></label><label>Ne bilmemizi istersin?<textarea required value={text} onChange={e=>setText(e.target.value)} maxLength={15000}/></label><button className="button secondary" disabled={busy}>Bilgiyi ekle</button></form>}</details>;
}
